import os, glob

ROOT = r"D:\wqz\code\NoCodeMotion"
ZW = "\u200b"  # 零宽字符：插在每个字符之间，使"查找替换"无法整体命中
PLAIN = "温启志编写，微信：18719361399"
OBF = ZW.join(PLAIN)                 # 混淆后的联系方式（渲染正常，文本搜索匹配不到）
NOTE = "※" + ZW.join("保留所有权利请勿删除")
BOX = "═" * 61
COMMENT = (
    f"// {BOX}\n"
    f"// {OBF}　{NOTE}\n"
    f"// {BOX}"
)

def detect_codec(b):
    if b[:3] == b"\xef\xbb\xbf":
        return "utf-8-sig"
    try:
        b.decode("utf-8")
        return "utf-8"
    except UnicodeDecodeError:
        return "gbk"

def dominant_newline(text):
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    return "\r\n" if crlf >= lf else "\n"

inserted, skipped, encrypted, autogen = 0, 0, 0, 0
for f in glob.glob(os.path.join(ROOT, "**", "*.cs"), recursive=True):
    rel = os.path.relpath(f, ROOT)
    if any(p in rel for p in ("bin", "obj", ".workbuddy")):
        continue
    with open(f, "rb") as fh:
        raw = fh.read()
    if raw[:1] == b"\x88":
        encrypted += 1
        continue
    codec = detect_codec(raw)
    text = raw.decode(codec)
    head = text[:1500]
    if "<auto-generated>" in head or rel.endswith(".g.cs"):
        autogen += 1
        continue
    if "温启志" in text or OBF in text:
        skipped += 1
        continue
    nl = dominant_newline(text)
    body = text
    # 去掉前导 BOM 以便拼接（写入时再按 codec 加回）
    if codec == "utf-8-sig" and body.startswith("\ufeff"):
        body = body[1:]
    new_body = COMMENT + nl + body
    if codec == "gbk":
        out = new_body.encode("utf-8-sig")   # GBK 无法表示零宽/制表符，升级为 UTF-8(BOM)
    else:
        out = new_body.encode(codec)         # utf-8 / utf-8-sig 保持原样
    with open(f, "wb") as fh:
        fh.write(out)
    inserted += 1

print(f"INSERTED={inserted} SKIPPED={skipped} ENCRYPTED={encrypted} AUTOGEN={autogen}")
