﻿// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ◆温⁠启‎志‎◆‎编⁠写​◇⁣微‌信⁠﹕‍1‎8‎7‌◆‏1​9‌3‍6‍◇‏1‌3‌9‏9‌　​※⁣保‌留‏所‏有⁣权‏利⁠请⁠勿‏删‎除‎◇​⁣​
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ────────────────────────────────────────────────────────────────
// 移植自 WenQiZhiMotion / SMotorse 运动控制卡层参考实现
//   源: IAxis/CAxisParameter.cs
//   改动: 仅行尾归一化为 LF、加 #nullable disable；命名空间与逻辑保持原样。
// ────────────────────────────────────────────────────────────────
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace WenQiZhi.Domain.MotionCard.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

    public class CAxisParameter
    {

        #region 轴脉冲输出模式

        /// <summary>
        /// 最大速度
        /// </summary>
        [DisplayName("轴脉冲输出模式"), Description("轴脉冲输出模式，包括两种类型：脉冲方向和双脉冲，共6种细分类"), Category("轴脉冲输出模式"), Browsable(false)]
        public PlusOutModeEnum POutMode { get; set; } = PlusOutModeEnum.OUT_DIR;


        #endregion

        #region 速度参数
        /// <summary>
        /// 最大速度
        /// </summary>
        [DisplayName("最大速度"), Description("设置该轴的最大速度,单位plus/s，缺省值2M"), Category("速度参数"), Browsable(false)]
        public double MaxVel { get; set; } = 1024 * 1024 * 2;

        /// <summary>
        /// 最大停止速度
        /// </summary>
        [DisplayName("最大停止速度"), Description("设置该轴的最大停止速度,单位plus/s，缺省值2M"), Category("速度参数"), Browsable(false)]
        public double MaxStopVel { get; set; } = 1024 * 1024 * 2;

        /// <summary>
        /// 最大加速度时间
        /// </summary>
        [DisplayName("最大加速度时间"), Description("设置该轴的最大加速度时间，单位秒"), Category("速度参数"), Browsable(false)]
        public double MaxAcc { get; set; } = 1000;

        /// <summary>
        /// 最大减速度时间
        /// </summary>
        [DisplayName("最大减速度时间"), Description("设置该轴的最大减速度时间，单位秒"), Category("速度参数"), Browsable(false)]
        public double MaxDec { get; set; } = 1000;


        /// <summary>
        /// 最小加速度时间
        /// </summary>
        [DisplayName("最小加速度时间"), Description("设置该轴的最小加速度时间，单位秒"), Category("速度参数"), Browsable(false)]
        public double MinAcc { get; set; } = 0.001;

        /// <summary>
        /// 最小减速度时间
        /// </summary>
        [DisplayName("最小减速度时间"), Description("设置该轴的最小减速度时间，单位秒"), Category("速度参数"), Browsable(false)]
        public double MinDec { get; set; } = 0.001;



        /// <summary>
        /// 起始速度
        /// </summary>
        [DisplayName("起始速度"), Description("起始速度(初速度)。该值必须小于或者等于运行速度。单位：pulse/s (最大值为 2M) 默认值3000"), Category("速度参数"), Browsable(false)]
        public double StartVel { get; set; } = 3000.00;

        /// <summary>
        /// 运行速度
        /// </summary>
        [DisplayName("运行速度"), Description("起始速度(初速度)。该值必须小于或者等于运行速度。单位：pulse/s (最大值为 2M) 默认值4000"), Category("速度参数"), Browsable(false)]
        public double RunVel { get; set; } = 4000.00;

        /// <summary>
        /// 加速度
        /// </summary>
        [DisplayName("加速度"), Description("设置该轴的加速度（单位：s ,最小值为 0.001s)）,默认值1"), Category("速度参数"), Browsable(false)]
        public double Acc { get; set; } = 1.00;

        /// <summary>
        /// 减速度
        /// </summary>
        [DisplayName("减速度"), Description("设置该轴的减速度（单位：s ,最小值为 0.001s）,默认值1"), Category("速度参数"), Browsable(false)]
        public double Dec { get; set; } = 1.00;


        /// <summary>
        /// S段速度
        /// </summary>
        [DisplayName("S段速度"), Description("设置该轴的S段速度（单位：s；范围：0~0.5 s）默认值0"), Category("速度参数"), Browsable(false)]
        public double SPara { get; set; } = 0;

        /// <summary>
        /// 速度类型
        /// </summary>
        [DisplayName("速度类型"), Description("设置速度类型：梯形或者S型。取值1为S型，默认值为0(梯形)"), Category("速度参数"), Browsable(false)]
        public int JK { get; set; } = 0;


        /// <summary>
        /// 停止速度
        /// </summary>
        [DisplayName("停止速度"), Description("停止速度。该值必须小于或者等于运行速度。默认值1000"), Category("速度参数"), Browsable(false)]
        public double StopVel { get; set; } = 1000.00;

        #endregion


        #region 脉冲当量
        /// <summary>
        /// 单位数量, 脉冲当量=单位数量/单位名称值
        /// </summary>
        [DisplayName("UnitNum"), Description("脉冲当量=单位数量/单位名称值, 例如此轴10000个脉冲转一圈，则单位数量填10000"), Category("脉冲当量设置"), Browsable(false)]
        public double UnitNum { get; set; } = 1;

        /// <summary>
        /// 单位名称值, 脉冲当量=单位数量/单位名称值
        /// </summary>
        [DisplayName("UnitDenom"), Description("脉冲当量=单位数量/单位名称值,例如丝杆导程10mm，则单位名称值填10"), Category("脉冲当量设置"), Browsable(false)]
        public double UnitDenomValue { get; set; } = 1;

        /// <summary>
        /// 单位名称
        /// </summary>
        [DisplayName("UnitType"), Description("脉冲当量=单位数量/单位名称值,例如丝杆导程10mm，则单位名称填mm"), Category("脉冲当量设置"), Browsable(false)]
        public UnitDenomEnumName UnitDenom { get; set; } = UnitDenomEnumName.pulse;

        /// <summary>
        /// 正方向距离值
        /// </summary>
        [DisplayName("正方向距离值"), Description("正方向距离值,回原完成，当前编码器0到达正限位距离"), Category("脉冲当量设置"), Browsable(false)]
        public double PositiveDirectionValue { get; set; } = 10000;

        /// <summary>
        /// 负方向距离值
        /// </summary>
        [DisplayName("负方向距离值"), Description("负方向距离值,回原完成，当前编码器0到达负限位距离"), Category("脉冲当量设置"), Browsable(false)]
        public double NegativeDirectionValue { get; set; } = -10000;

        #endregion

        #region 轴初始判定标记

        [DisplayName("是否确定轴参数初始化完成"), Description("当前轴是否初始化参数设定完成"), Category("初始化相关设置"), Browsable(true)]
        /// <summary>
        /// 是否允许编码器
        /// </summary>
        public bool InitEnable { get; set; } = false;

        #endregion

        #region 回原设置
        /// <summary>
        /// EZ信号电平
        /// </summary>
        [DisplayName("EZ信号电平"), Description("设置Z相信号的有效逻辑电平。在运动控制中，Z相信号常用于回原。true设置为高平，false为低电平"), Category("回原设置"), Browsable(true)]
        public bool EZLogic { get; set; } = false;

        /// <summary>
        /// ORG电平
        /// </summary>
        [DisplayName("ORG电平"), Description("设置ORG信号的有效逻辑电平，true为高电平，false为低电平"), Category("回原设置"), Browsable(true)]
        public bool ORGLogic { get; set; } = false;

        /// <summary>
        /// ORG停止模式
        /// </summary>
        [DisplayName("ORG停止模式"), Description("设置回原点运动结束时的停止模式，0为减速停止，1为急停"), Category("回原设置"), Browsable(true)]
        public int ORGMode { get; set; } = 0;

        /// <summary>
        /// 复位计数器开关
        /// </summary>
        [DisplayName("复位计数器开关"), Description("使能/禁用该轴回原运动后复位逻辑计数器。true使能，false禁用"), Category("回原设置"), Browsable(true)]
        public bool HomeReset { get; set; } = true;

        /// <summary>
        /// 回原模式
        /// </summary>
        [DisplayName("回原模式"), Description("设置回原运动中的回原模式， MODE1_Abs, MODE2_NegLimitSignal, MODE2_PosLimitSignal, MODE3_LimitSignalAndORG"), Category("回原设置"), Browsable(true)]
        public HomeModeEnum HomeMode { get; set; } = 0;

        /// <summary>
        /// 回原速度,0低速度，1高速
        /// </summary>
        [DisplayName("回原速度"), Description("设置回原速度，0低速度，1高速"), Category("回原设置"), Browsable(true)]
        public int HomeSpeed { get; set; } = 0;


        /// <summary>
        /// 回原点完成后的偏移量
        /// </summary>
        [DisplayName("回原点完成后的偏移量"), Description("回原点完成后，再走一定距离，然后脉冲位置与编码器位置置0"), Category("回原设置"), Browsable(true)]
        public double HomeOffSet { get; set; } = 50;

        /// <summary>
        /// 感应负限后的移动距离
        /// </summary>
        [DisplayName("感应负限后的移动距离"), Description("感应负限后的移动距离"), Category("回原设置"), Browsable(true)]
        public double HomeTrigNegMove { get; set; } = 50;


        /// <summary>
        /// 感应正限后的移动距离
        /// </summary>
        [DisplayName("感应正限后的移动距离"), Description("感应正限后的移动距离"), Category("回原设置"), Browsable(true)]
        public double HomeTrigPosMove { get; set; } = 1000;


        /// <summary>
        /// 回原超时时间
        /// </summary>
        [DisplayName("回原超时时间"), Description("回原超时时间，填写时间数来能超过0，进行超时判断，单位毫秒ms"), Category("回原设置"), Browsable(false)]
        public int HomeOvertime { get; set; } = 0;



        /// <summary>
        /// 在原点时回原，先移动的距离
        /// </summary>
        [DisplayName("在原点时回原先移动的距离"), Description("在原点时回原时，先移动一定距离，再回原"), Category("回原设置"), Browsable(true)]
        public double HomeTrigHomeMove { get; set; } = 1000;


        /// <summary>
        /// 回原点的距离（回原点时，最多走的距离，仅在非MODE1_Abs回原模式下有效）
        /// </summary>
        [DisplayName("回原点的距离"), Description("回原点的距离（回原点时，最多走的距离，仅在非MODE1_Abs回原模式下有效）"), Category("回原设置"), Browsable(true)]
        public double HomeDistance { get; set; } = -110000;


        /// <summary>
        /// 最多回原点的次数
        /// </summary>
        [DisplayName("最多回原点的次数"), Description("最多回原点的次数"), Category("回原设置"), Browsable(true)]
        public int MaxHomeTimes { get; set; } = 3;

        /// <summary>
        /// 回原方向 0负方向，1正方向。
        /// </summary>
        [DisplayName("回原方向"), Description("回原方向，不同卡值不同。0负方向，1正方向。"), Category("回原设置"), Browsable(true)]
        public int HomeDir { get; set; } = 0;

        #endregion



        #region 回原速度
        /// <summary>
        /// home起始速度
        /// </summary>
        [DisplayName("home起始速度"), Description("设置Home运动的低速（起始速度），此值必须小于等于“运行速度”，默认值2000。"), Category("回原速度设置"), Browsable(true)]
        public double HomeStartVel { get; set; } = 2000.00;

        /// <summary>
        /// home运行速度
        /// </summary>
        [DisplayName("home运行速度"), Description("设置Home运动的高速（运行速度），此值必须小于等于“最大速度”，大于等于“起始速度”，默认值8000。"), Category("回原速度设置"), Browsable(true)]
        public double HomeRunVel { get; set; } = 8000.00;


        /// <summary>
        /// 总线卡最小回原速度
        /// </summary>
        [DisplayName("总线卡最小回原速度"), Description("设置EtherCAT总线卡最小回原速度"), Category("回原设置"), Browsable(true)]
        public double EtherCATHomeMinSpeed { get; set; } = 10;

        /// <summary>
        /// 总线卡最大回原速度
        /// </summary>
        [DisplayName("总线卡最大回原速度"), Description("设置EtherCAT总线卡最大回原速度"), Category("回原设置"), Browsable(true)]
        public double EtherCATHomeMaxSpeed { get; set; } = 30;

        /// <summary>
        /// 总线卡回零偏移
        /// </summary>
        [DisplayName("总线卡回零偏移"), Description("设置EtherCAT 总线卡回零偏移"), Category("回原设置"), Browsable(true)]
        public double EtherCATHomeOffset { get; set; } = 0;


        /// <summary>
        /// home加速度
        /// </summary>
        [DisplayName("home加速度"), Description("设置Home运动的加速度。此值必须小于等于“最大加速度”，默认值1"), Category("回原速度设置"), Browsable(true)]
        public double HomeAcc { get; set; } = 0.2;

        /// <summary>
        /// home减速度
        /// </summary>
        [DisplayName("home减速度"), Description("设置Home运动的减速度。此值必须小于等于“最大减速度”，默认值1"), Category("回原速度设置"), Browsable(true)]
        public double HomeDec { get; set; } = 0.1;

        /// <summary>
        /// home速度类型
        /// </summary>
        [DisplayName("home速度类型"), Description("设置速度类型：梯形或者S型。取值1为S型，默认值为0(梯形)"), Category("回原速度设置"), Browsable(true)]
        public int HomeJK { get; set; } = 0;
        #endregion


        #region 锁存功能
        /// <summary>
        /// 锁存信号电平
        /// </summary>
        [DisplayName("锁存信号电平"), Description("设置锁存信号的逻辑有效电平，true为高电平，false为低电平"), Category("锁存设置"), Browsable(false)]
        public bool LTCLogic { get; set; } = false;

        /// <summary>
        /// 锁存开关
        /// </summary>
        [DisplayName("锁存开关"), Description("使能/禁用锁存功能。true使能，false禁用。启用锁存功能后，一旦IN1端口接收到有效电平，控制器会立即锁存指令理论位置值/编码器实际位置值"), Category("锁存设置"), Browsable(false)]
        public bool LTCEnable { get; set; } = false;
        #endregion


        #region 软件限位
        /// <summary>
        /// 软件负限位开关
        /// </summary>
        [DisplayName("软件负限位开关"), Description("使能/禁用该轴的负向软件极限。true使能，false禁用。启用负方向软限位功能后，负向移动的电机指令位置达到SNEL设定的值后，已达会被控制停止运动。"), Category("软件限位设置"), Browsable(false)]
        public bool SoftNELEnable { get; set; } = false;

        /// <summary>
        /// 软件正限位开关
        /// </summary>
        [DisplayName("软件正限位开关"), Description("使能/禁用该轴的负向软件极限。true使能，false禁用。启用正方向软限位功能后，正向移动的电机指令位置达到SNEL设定的值后，已达会被控制停止运动。"), Category("软件限位设置"), Browsable(false)]
        public bool SoftPELEnable { get; set; } = false;

        /// <summary>
        /// 软负限位值
        /// </summary>
        [DisplayName("软负限位值"), Description("设置负向软件极限值"), Category("软件限位设置"), Browsable(false)]
        public double SNEL { get; set; } = -1000000;

        /// <summary>
        /// 软正限位值
        /// </summary>
        [DisplayName("软正限位值"), Description("设置正向软件极限值"), Category("软件限位设置"), Browsable(false)]
        public double SPEL { get; set; } = 1000000;

        /// <summary>
        /// 软限位停止模式
        /// </summary>
        [DisplayName("软限位停止模式"), Description("设置软件极限触发时电机停止模式，0为减速停止，1为急停"), Category("软件限位设置"), Browsable(false)]
        public int SLimitMode { get; set; } = 1;

        /// <summary>
        /// 计数器选择，0：指令位置计数器，1：编码器计数器
        /// </summary>
        [DisplayName("软限位计数器选择"), Description("计数器选择，0：指令位置计数器，1：编码器计数器"), Category("软件限位设置"), Browsable(false)]
        public int SSourceSel { get; set; } = 0;

        ///// <summary>
        ///// 软正限位停止模式
        ///// </summary>
        //[DisplayName("软正限位停止模式"), Description("设置正向软件极限触发时电机停止模式，0为减速停止，1为急停"), Category("软件限位设置")]
        //public double SPELMode { get; set; } = 1;

        #endregion

        //todo: lqc 2023 0515 1520
        #region 硬件电平设置
        /// <summary>
        /// 软负限位值
        /// </summary>
        [DisplayName("限位电平"), Description("设置EL+，EL-的电平。注意对不同的运动卡取值不同。pci9104取值:0低电平,1高电平。 DMC2210取值：0,1,2,3。详细参见各卡的说明"), Category("硬件电平设置"), Browsable(false)]
        public ELLoGic1 ELLogic { get; set; } = ELLoGic1.Low_Level;

        public enum ELLoGic1 { Low_Level = 0, High_Level = 1 }

        [DisplayName("报警电平"), Description("设置ALM的逻辑电平, 0低电平,1高电平"), Category("硬件电平设置"), Browsable(false)]
        public ALMLogic1 ALMLogic { get; set; }

        public enum ALMLogic1 { Low_Level = 0, High_Level = 1 }

        [DisplayName("报警停轴方式(急停)"), Description("设置ALM的逻辑电平"), Category("硬件电平设置"), Browsable(false)]
        public ALMStopMode1 ALMStopMode { get; set; }

        public enum ALMStopMode1 { Low_Level = 0, High_Level = 1 }

        public enum OriginLogic1 { Low_Level = 0, High_Level = 1 }
        [DisplayName("原点电平"), Description("设置原点的逻辑电平"), Category("硬件电平设置"), Browsable(false)]
        public OriginLogic1 OriginLogic { get; set; }

        [DisplayName("报警使能"), Description("报警ALM使能，true使能，false禁用"), Category("硬件电平设置"), Browsable(false)]
        public bool ALMEnable { get; set; } = false;



        #endregion


        #region 其它设置



        [DisplayName("轴的自定义名称"), Description("轴的自定义名称"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 轴的自定义名称
        /// </summary>
        public int UserDefineName { get; set; }

        [DisplayName("轴运行状态"), Description("轴运行状态"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 轴运行状态
        /// </summary>
        public int RunState { get; set; }

        [DisplayName("使能状态"), Description("使能状态"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 使能状态
        /// </summary>
        public int Enable { get; set; }

        [DisplayName("位置"), Description("位置"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 位置
        /// </summary>
        public int Postion { get; set; }

        ///// <summary>
        ///// 脉冲当量
        ///// </summary>
        //public int Equiv { get; set; }

        [DisplayName("高电平/低电平"), Description("高电平/低电平"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 高电平/低电平
        /// </summary>
        public int Level { get; set; }

        [DisplayName("报警"), Description("报警"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// 报警
        /// </summary>
        public int Alarm { get; set; }

        [DisplayName("EtherCAT总线轴地址"), Description("EtherCAT 总线轴地址"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// EtherCAT 总线轴地址
        /// </summary>
        public int SlaveAddr { get; set; }

        [DisplayName("EtherCAT总线子地址"), Description("EtherCAT总线子地址"), Category("其它设置"), Browsable(false)]
        /// <summary>
        /// EtherCAT 总线轴子地址
        /// </summary>
        public int SubSlaveAddr { get; set; }
        #endregion


        #region 编码器相关设置

        [DisplayName("是否允许编码器"), Description("当前轴是否允许编码器"), Category("编码器相关设置"), Browsable(false)]
        /// <summary>
        /// 是否允许编码器
        /// </summary>
        public bool EncodeEnable { get; set; } = true;


        [DisplayName("编码器位置误差最大值"), Description("编码器位置误差最大值，规划位置减去编码器位置的误差大于这个值则应该报警"), Category("编码器相关设置"), Browsable(false)]
        /// <summary>
        /// 规划位置减去编码器位置的误差大于这个值则应该报警
        /// </summary>
        public double Deviation { get; set; } = 20;


        [DisplayName("是否Mapping允许编码器"), Description("当前轴是否允许编码器，用于Mapping操作使用"), Category("编码器相关设置"), Browsable(false)]
        /// <summary>
        /// 是否允许编码器,Mapping应用
        /// </summary>
        public bool EncodeEnableTouchMode { get; set; } = true;

        [DisplayName("是否允许用户点击清零按钮"), Description("当前轴是否允许用户点击清零按钮,清除编码器值和指令位置,true=就是不允许,"), Category("轴权限相关设置"), Browsable(true)]
        /// <summary>
        /// 是否允许用户点击清零按钮
        /// </summary>
        public bool EncodeEnableClearBtn { get; set; } = false;

        [DisplayName("是否允许用户点击回原按钮"), Description("当前轴是否允许用户点击回原按钮,让轴回原,true=就是不允许,"), Category("轴权限相关设置"), Browsable(true)]
        /// <summary>
        /// 是否允许用户点击清零按钮
        /// </summary>
        public bool EncodeEnableHomeBtn { get; set; } = false;
        #endregion


        #region 虚拟轴调试用专用参数

        //使用虚拟运动卡的时候，可以设置调试参数，以模拟测试

        [DisplayName("正限位脉冲位置"), Description("正限位脉冲位置"), Category("虚拟轴调试用专用参数"), Browsable(false)]
        /// <summary>
        ///正限位脉冲位置
        /// </summary>
        public int PELPlusPos { get; set; } = 1000000000;

        [DisplayName("负限位脉冲位置"), Description("负限位脉冲位置"), Category("虚拟轴调试用专用参数"), Browsable(false)]
        /// <summary>
        ///负限位脉冲位置
        /// </summary>
        public int MELPlusPos { get; set; } = -1000000000;

        [DisplayName("原点脉冲位置"), Description("原点脉冲位置"), Category("虚拟轴调试用专用参数"), Browsable(false)]
        /// <summary>
        ///原点脉冲位置
        /// </summary>
        public int ORGPlusPos { get; set; }


        //[DisplayName("正机械限位脉冲位置"), Description("正机械限位脉冲位置"), Category("虚拟轴调试用专用参数")]
        ///// <summary>
        /////正机械限位脉冲位置
        ///// </summary>
        //public int PELAlarmPlusPos { get; set; }


        //[DisplayName("负机械限位脉冲位置"), Description("负机械限位脉冲位置"), Category("虚拟轴调试用专用参数")]
        ///// <summary>
        /////负机械限位脉冲位置
        ///// </summary>
        //public int NELAlarmPlusPos { get; set; }


        #endregion


        #region 轴互斥项
        [DisplayName("轴互斥条件项"), Description("当前轴是否存在互斥项，进行填写对应的条件。(条件：手动填写，多个条件用英文逗号【,】分割开来)"), Category("轴互斥条件设置"), Browsable(false)]
        /// <summary>
        /// 条件
        /// </summary>
        public string AxisMutexConditions { get; set; } = "";

        [DisplayName("轴互斥条件项"), Description("当前轴互斥条件返回状态，0：判断条件失败  1：判断条件成功"), Category("轴互斥条件设置"), Browsable(false)]
        /// <summary>
        /// 当前轴互斥条件返回状态，0：判断条件失败  1：判断条件成功
        /// </summary>
        public int AxisMutexResult { get; set; } = 0;

        #endregion

        #region 点位前置条件参数
        [DisplayName("点位前置条件"), Description("当前轴运动前的前置条件.(条件：不需要在此界面手动填写,由点位表UI设置后自动生成，多个条件用英文逗号【,】分割开来)"), Category("轴运动前的前置条件"), Browsable(false)]

        /// <summary>
        /// 当前轴运动前的前置条件
        /// </summary>
        public string AxisMutexPrecondition { get; set; } = "";

        #endregion

        #region

        [DisplayName("轴偏移开关，急停/复位后自动关闭"), Description("轴偏移开关，使用请使用LUA脚本API进行修改开关使用，使用完毕进行关闭，否则所有点位都会进行偏移"), Category("轴偏移设置"), ReadOnly(true), Browsable(true)]
        /// <summary>
        /// 当前轴互斥条件返回状态，0：判断条件失败  1：判断条件成功
        /// </summary>
        public bool AxisOffsetSW { get; set; } = false;
        [DisplayName("轴偏移数值"), Description("轴偏移数值，每个PMove Pt都会进行偏移"), Category("轴偏移设置"), ReadOnly(true), Browsable(true)]
        /// <summary>
        /// 当前轴互斥条件返回状态，0：判断条件失败  1：判断条件成功
        /// </summary>
        public double AxisOffsetValue { get; set; } = 0;
        #endregion
    }
}
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓​⁣​
