﻿// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ◆温⁠启‎志‎◆‎编⁠写​◇⁣微‌信⁠﹕‍1‎8‎7‌◆‏1​9‌3‍6‍◇‏1‌3‌9‏9‌　​※⁣保‌留‏所‏有⁣权‏利⁠请⁠勿‏删‎除‎◇​⁣​
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ────────────────────────────────────────────────────────────────
// 移植自 WenQiZhiMotion / SMotorse 运动控制卡层参考实现
//   源: IAxis/IAxis.cs
//   改动: 仅行尾归一化为 LF、加 #nullable disable；命名空间与逻辑保持原样。
// ────────────────────────────────────────────────────────────────
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace WenQiZhi.Domain.MotionCard.Common
{

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public interface IAxis
    {
        #region AD,DA功能

        /// <summary>
        /// 设置 DA 输出使能
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="enable">DA 使能状态，0：禁止，1：使能</param>
        /// <returns>错误代码</returns>
        int SetCardDAEnable(int CardNo, int enable);

        /// <summary>
        /// 读取 DA 输出使能设置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="enable">DA 使能状态，0：禁止，1：使能</param>
        /// <returns>错误代码</returns>
        int GetCardDAEnable(int CardNo, ref UInt16 enable);

        /// <summary>
        /// 设置 DA 输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA 输出口号，取值范围 0、1</param>
        /// <param name="Vout">DA 输出电压，输出电压范围 -10V ~ 10V</param>
        /// <returns>错误代码</returns>
        int SetCardDAOutPut(int CardNo, int channel, double Vout);

        /// <summary>
        /// 读取 DA 输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA 输出口号，取值范围 0、1</param>
        /// <param name="Vout">DA 输出电压，输出电压范围 -10V ~ 10V</param>
        /// <returns>错误代码</returns>
        int GetCardDAOutPut(int CardNo, int channel, ref double Vout);

        /// <summary>
        /// 读取 AD 输入
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">AD 输入口号，取值范围 0 ~ 7</param>
        /// <param name="Vout">AD 输入电压，输入电压范围 -10V ~ 10V</param>
        /// <returns>错误代码</returns>
        int GetCardADInPut(int CardNo, int channel, ref double Vout);


        /// <summary>
        /// 读取AD输入(电流)；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">AD 输入口号，取值范围 0 ~ 7</param>
        /// <param name="Vout">AD 输入电压，输入电流范围-20mA-20mA；电流最大为20mA；</param>
        /// <returns>错误代码</returns>
        int GetCardADInPutEx(int CardNo, int channel, ref double Vout);

        #endregion


        #region 单轴运动

        /// <summary>
        /// 启动轴的点位运动
        /// </summary>
        /// <returns></returns>
        int CardAxisPointMovement(MotionParamModel mpm);

        /// <summary>
        /// 启动轴的连续运动
        /// </summary>
        /// <returns></returns>
        int CardAxisSerialMovement(MotionParamModel mpm);

        /// <summary>
        /// 在线改变指定轴的当前运动速度
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="Curr_Vel">改变后的运动速度，单位：pulse/s</param>
        /// <param name="Taccdec">保留参数，固定值为 0</param>
        /// <returns>错误代码</returns>
        int CardAxisChangeSpeed(int CardNo, int axis, double Curr_Vel, double Taccdec);

        /// <summary>
        /// 在线改变指定轴的当前目标位置
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="dist">目标位置，单位：pulse</param>
        /// <param name="posi_mode">保留参数，固定值为 0</param>
        /// <returns>错误代码</returns>
        int CardAxisResetTargetPosition(int CardNo, int axis, int dist, int posi_mode);

        /// <summary>
        /// 强行改变指定轴的当前目标位置（在线/非在线）
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="dist">目标位置，单位：pulse</param>
        /// <param name="posi_mode">保留参数，固定值为 0</param>
        /// <returns>错误代码</returns>
        int CardAxisUpdateTargetPosition(int CardNo, int axis, int dist, int posi_mode);

        #endregion


        #region 插补运动

        /// <summary>
        /// 设置直线插补的速度
        /// </summary>
        /// <param name="parameter"></param>
        /// <returns></returns>
        int CardAxisLineUnitSpeed(LineInterpolateparamModel parameter);

        /// <summary>
        /// 读取插补运动速度
        /// <para>注 意：</para>
        /// <para>该函数不适用于连续插补</para>
        /// </summary>
        /// <param name="mpm">运动参数
        /// <para>"CardNo"卡号</para>
        /// <para>"axis"指定轴号</para>
        /// <para>"MinVel"返回起始速度设置，单位：unit/s</para>
        /// <para>"MaxVel"返回最大速度设置，单位：unit/s</para>
        /// <para>"TaccVel"返回加速时间设置，单位：s</para>
        /// <para>"TdecVel"返回减速时间设置，单位：s</para>
        /// <para>"StopVel"返回停止速度设置，单位：unit/s</para></param>
        /// <returns>错误代码</returns>
        MotionParamModel GetCardAxisAccVel(MotionParamModel mpm);

        /// <summary>
        /// 启动直线插补
        /// </summary>
        /// <param name="line"></param>
        /// <returns></returns>
        int CardAxisLineUnit(LineInterpolateparamModel line);

        /// <summary>
        /// 启动圆弧插补
        /// <para>基于圆心圆弧扩展的螺旋线插补运动（圆心终点式圆弧/螺旋线/渐开线 ）（可作两轴圆弧插补） </para>
        /// <para>注  意：</para> 
        /// <para> 1） 当轴数为 2 时，轴列表前两轴进行平面螺旋</para>
        /// <para> 2） 当轴数为 3、运动轨迹为螺旋插补时，轴列表前两轴平面为基面，进行平面螺旋插补；同时，轴列表第三轴运动指定高度，该轴终点位置与该轴起点位置的差值为螺旋线段相对于基面的高度</para>
        /// <para> 3） 当轴数大于 3、运动轨迹为螺旋插补时，列表前三轴进行螺旋插补的同时，后续轴做线性跟随运动，运动时间与前三轴的运动时间相等</para>
        /// <para> 4） 当运动轨迹为螺旋插补时：</para>
        ///  <para>   轴列表前两轴组成的基面上，当起始点到圆心的距离小于终点到圆心的距离，为绽放螺旋线</para>
        ///  <para>   轴列表前两轴组成的基面上，当起始点到圆心的距离大于终点到圆心的距离，为收敛螺旋线</para>
        ///  <para>   轴列表前两轴组成的基面上，当起始点到圆心的距离等于终点到圆心的距离，为圆弧插补（插补轴数为 3 时则为圆柱螺旋线）</para>
        /// </summary>
        int CardAxisArcMoveCenterUnit(ArcInterpolateparamModel arc);

        #endregion


        #region 一维单轴低速位置比较

        /// <summary>
        /// 一维低速位置比较:设置一维位置比较输出数据
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="enable">比较功能状态，0：禁止，1：使能</param>
        /// <param name="cmp_source">比较源，0：指令位置计数器，1：编码器计数器</param>
        /// <returns>错误代码</returns>
        int SetCardAxisCompareConfigDate(int CardNo, int axis, int enable, int cmp_source);

        /// <summary>
        /// 一维低速位置比较: 读取一维位置比较器设置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="enable">返回比较功能状态</param>
        /// <param name="cmp_source">返回比较源</param>
        /// <returns>错误代码</returns>
        int GetCardAxisCompareConfig(int CardNo, int axis, ref UInt16 enable, ref UInt16 cmp_source);

        /// <summary>
        /// 一维低速位置比较：查询可以加入的一维比较点个数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="pointNum">返回可以加入的比较点数</param>
        /// <returns>错误代码</returns>
        int GetCardAxisComparePointsRemained(int CardNo, int axis, ref int pointNum);

        /// <summary>
        /// 一维低速：读取当前一维比较点位置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="pos">返回当前比较点位置，单位：pulse</param>
        /// <returns>错误代码</returns>
        int GetCardAxisCompareCurrentPoint(int CardNo, int axis, ref int pos);

        /// <summary>
        /// 一维低速位置比较：查询已经比较过的一维比较点个数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="pointNum">返回已经比较过的点数</param>
        /// <returns>错误代码</returns>
        int GetCardAxisComparePointsRunned(int CardNo, int axis, ref int pointNum);



        /// <summary>
        /// 一维低速位置比较：设置一维位置比较器 
        /// <para>注 意：</para><para>DMC3C00 后四轴不支持位置比较功能</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="enable">比较功能状态，0：禁止，1：使能 </param>
        /// <param name="cmp_source">   比较源，0：指令位置计数器，1：编码器计数器</param>
        /// <returns>错误代码</returns>
        int SetCardAxisCompareConfig(int CardNo, int axis, int enable, int cmp_source);

        /// <summary>
        /// 一维低速位置比较：添加一维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="pos">比较位置，单位：pulse</param>
        /// <param name="dir">比较模式，0：小于等于，1：大于等于</param>
        /// <param name="action">比较点触发功能编号</param>
        /// <param name="actpara">比较点触发功能参数</param>
        /// <returns>错误代码</returns>
        int AddCardAxisComparePoint(int CardNo, int axis, int pos, int dir, UInt16 action, UInt32 actpara);

        /// <summary>
        /// 一维低速位置比较：清除已添加的所有一维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <returns>错误代码</returns>
        int ClearCardAxisComparePoints(int CardNo, int axis);

        /// <summary>
        /// 多维低速位置比较：设置多维位置比较器 
        /// <para>注 意：</para><para>DMC3C00 后四轴不支持位置比较功能</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="cmper_No">比较器号：0~1</param>
        /// <param name="axis_List">比较轴数组</param>
        /// <param name="enable">比较功能状态，0：禁止，1：使能 </param>
        /// <param name="cmp_source">   比较源，0：指令位置计数器，1：编码器计数器</param>
        /// <returns>错误代码</returns>
        int SetCardMulAxisCompareConfig(int CardNo, int cmper_No, int[] axis_List, int enable, int cmp_source);

        /// <summary>
        /// 多维低速位置比较：添加多维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="cmper_No">比较器号：0~1</param>
        /// <param name="dir">比较模式，0：大于等于，1：小于等于</param>
        /// <param name="action">比较点触发功能编号</param>
        /// <param name="actpara">比较点触发功能参数，脉冲宽度</param>
        /// <param name="bitNo">输出IO bit</param>
        /// <param name="cmp_pos">点位数组</param>
        /// <returns>错误代码</returns>
        int AddCardMulAxisComparePoint(int CardNo, int cmper_No, int dir, UInt16 action, UInt32 actpara, int bitNo, double[] cmp_pos);

        /// <summary>
        /// 多维低速位置比较：清除已添加的所有多维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="cmper_No">比较器号：0~1</param>
        /// <returns>错误代码</returns>
        int ClearCardMulAxisComparePoints(int CardNo, int cmper_No);

        #endregion

        #region 一维单轴高速位置比较输出

        /// <summary>
        /// 一维高速位置比较：开启\关闭(单轴高速)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400ASDK：0~3</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <param name="cmp_mode">比较模式：0：禁止（默认值）1：等于 2：小于 3：大于 4：队列 5：线性</param>
        /// <returns>错误代码</returns>
        int SetCardHcmpEnable(int CardNo, int axis, int hcmp, int cmp_mode = 0);


        /// <summary>
        /// 一维高速位置比较：配置高速比较
        /// <para>注 意：</para><para>DMC3C00 后四轴不支持位置比较功能</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400ASDK：0~3</param>
        /// <param name="enable">比较功能状态，0：禁止，1：使能 </param>
        /// <param name="cmp_source">   比较源，0：指令位置计数器，1：编码器计数器</param>
        /// <returns>错误代码</returns>
        int OpenCardHighCompareConfig(int CardNo, int hcmp, int axis, int cmp_source, int cmp_logic, long time);


        /// <summary>
        /// 一维高速位置比较：设置高速比较线性模式参数    
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <param name="Increment">位置增量值，单位：pulse（正值表示位置递增，负值表示位置递减）</param>
        /// <param name="Count">比较次数，取值范围：1~32767</param>
        /// <returns>错误代码</returns>
        int SetCardHcmpLiner(int CardNo, int hcmp, int Increment, int Count);

        /// <summary>
        /// 一维高速位置比较：清除所有已添加的高速位置比较器
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <returns>错误代码</returns>
        int ClearCardHcmpPoints(int CardNo, int hcmp);


        /// <summary>
        /// 一维高速位置比较：添加/更新高速比较位置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <param name="cmp_pos">队列模式下：添加比较位置，单位：pulse ; 线性模式下：更新起始比较位置，单位：pulse; 其他模式下：更新比较位置，单位：pulse</param>
        /// <returns>错误代码</returns>
        int AddCardHcmpPoint(int CardNo, int hcmp, int cmp_pos);

        /// <summary>
        /// 一维高速位置比较：读取高速比较参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <param name="remained_points">返回可添加比较点数</param>
        /// <param name="current_point">返回当前比较点位置，单位：pulse</param>
        /// <param name="runned_points">返回已比较点数</param>
        /// <returns>错误代码</returns>
        int GetCardHcmpCurrentState(int CardNo, int hcmp, ref int remained_points, ref int current_point, ref int runned_points);

        /// <summary>
        /// 一维高速位置比较：控制指定 CMP 端口的输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <param name="on_off">设置 CMP 端口电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        int SetCardHcmpCmpPin(int CardNo, int hcmp, int on_off);

        /// <summary>
        /// 一维高速位置比较：读取指定 CMP 端口的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">高速比较器，取值范围：0~3（对应硬件 CMP0~CMP3 端口）</param>
        /// <returns>CMP 端口电平</returns>
        int GetCardHcmpCmpPin(int CardNo, int hcmp);



        #endregion


        #region 二维高速位置比较输出

        /// <summary>
        /// 二维高速比较：设置高速比较使能
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="cmpEnable">二维高速比较器使能，0：禁止，1：使能</param>
        /// <returns>错误代码</returns>
        int SetCardAxisHcmp2dsetEnable(int CardNo, int hcmp, int cmpEnable);

        /// <summary>
        /// 二维高速比较：读取高速比较使能
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="hcmp"></param>
        /// <param name="cmpEnable"></param>
        /// <returns>错误代码</returns>
        int GetCardAxisHcmp2dsetEnable(int CardNo, int hcmp, ref ushort cmpEnable);

        /// <summary>
        /// 二维高速比较：配置高速比较器
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="cmp_mode">比较模式： 0：进入误差带后触发 1：进入误差带单轴等于后再触发</param>
        /// <param name="x_axis">x 轴关联轴号 DMC3400A：0~3，DMC3600：0~6，DMC3800/DMC3C00：0~8</param>
        /// <param name="cmp_source">x 轴比较位置源：0：指令位置，1：反馈位置</param>
        /// <param name="y_axis">y 轴关联轴号 轴号范围：DMC3400A：0~3，DMC3600：0~6，DMC3800/DMC3C00：0~8</param>
        /// <param name="y_cmp_source">y 轴比较位置源：0：指令位置，1：反馈位置</param>
        /// <param name="error">x/y 轴误差带设置，单位：pulse</param>
        /// <param name="cmp_logic">有效电平：0：低电平，1：高电平</param>
        /// <param name="time">脉冲宽度，单位：us，取值范围：1us~20s</param>
        /// <param name="pwm_enable">pwm 模式使能</param>
        /// <param name="duty">占空比</param>
        /// <param name="freq">频率</param>
        /// <param name="port_sel">输出口选择</param>
        /// <param name="pwm_number">输出的 pwm 脉冲数</param>
        /// <returns>错误代码</returns>
        int SetCardAxisHcmp2dsetConfig(int CardNo, ushort hcmp, ushort cmp_mode,
            ushort x_axis, ushort cmp_source, ushort y_axis, ushort y_cmp_source,
            int error, ushort cmp_logic, int time, ushort pwm_enable, double duty,
            int freq, ushort port_sel, ushort pwm_number);

        /// <summary>
        /// 二维高速比较：读取高速比较器
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="cmp_mode">返回 x 轴关联轴号</param>
        /// <param name="x_axis">返回 x 轴关联轴号</param>
        /// <param name="cmp_source">返回 x 轴比较位置源：0：指令位置，1：反馈位置</param>
        /// <param name="y_axis">返回 y 轴关联轴号</param>
        /// <param name="y_cmp_source">返回 y 轴比较位置源：0：指令位置，1：反馈位置</param>
        /// <param name="error">返回 x/y 轴误差带设置，单位：pulse</param>
        /// <param name="cmp_logic">返回有效电平：0：低电平，1：高电平</param>
        /// <param name="time">返回脉冲宽度，单位：us，取值范围：1us~20s</param>
        /// <param name="pwm_enable">pwm 模式使能</param>
        /// <param name="duty">占空比</param>
        /// <param name="freq">频率</param>
        /// <param name="port_sel">输出口选择</param>
        /// <param name="pwm_number">输出的 pwm 脉冲数</param>
        /// <returns>错误代码</returns>
        int GetCardAxisHcmp2dsetConfig(int CardNo, ushort hcmp, ref ushort cmp_mode,
               ref ushort x_axis, ref ushort cmp_source, ref ushort y_axis, ref ushort y_cmp_source,
               ref int error, ref ushort cmp_logic, ref int time, ref ushort pwm_enable, ref double duty,
               ref int freq, ref ushort port_sel, ref ushort pwm_number);

        /// <summary>
        /// 二维高速比较：清除所有缓冲区高速位置缓冲比较值，并退出当前比较状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <returns>错误代码</returns>
        int SetCardAxisHcmp2dClearPoints(int CardNo, ushort hcmp);

        /// <summary>
        /// 二维高速比较：添加/更新高速比较位置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="x_cmp_pos">队列模式下：添加 x 比较位置，单位：pulse</param>
        /// <param name="y_cmp_pos">队列模式下：添加 x 比较位置，单位：pulse</param>
        /// <returns>错误代码</returns>
        int SetCardAxisHcmp2dAddPoint(int CardNo, ushort hcmp, int x_cmp_pos, int y_cmp_pos);

        /// <summary>
        /// 二维高速比较：读取高速比较参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="remained_points">返回可添加比较点数</param>
        /// <param name="x_current_point">返回当前 x 比较点位置</param>
        /// <param name="y_current_point">返回当前 y 比较点位置</param>
        /// <param name="runned_points">返回已比较点数</param>
        /// <param name="current_state">比较器状态 1 正在输出 0 输出完成</param>
        /// <returns>错误代码</returns>
        int GetCardAxisHcmp2dCurrentState(int CardNo, ushort hcmp, ref int remained_points,
ref int x_current_point, ref int y_current_point, ref int runned_points, ref ushort current_state);

        /// <summary>
        /// 二维高速比较：该函数用于强制二维比较输出，输出按照配置好的脉冲模式或者 pwm 模式
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="hcmp">保留，参数值为 0</param>
        /// <param name="enable">强制二维比较输出，设置为 1 使能</param>
        /// <returns>错误代码</returns>
        int SetCardAxisHcmp2dForceOutput(int CardNo, ushort hcmp, ushort enable);

        #endregion

        #region 二维低速位置比较输出

        /// <summary>
        /// 二维低速位置比较：设置二维位置比较输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="enable">二维位置比较功能状态，0：禁止，1：使能 </param>
        /// <param name="cmp_source">二维位置比较源，0：指令位置计数器，1：编码器计数器</param>
        /// <returns>错误代码</returns>
        int SetCardCompareConfigExtern(int CardNo, int enable, int cmp_source);

        /// <summary>
        /// 二维低速位置比较：清除已添加的所有二维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <returns>错误代码</returns>
        int ClearCardComparePointsExtern(int CardNo);

        /// <summary>
        /// 二维低速位置比较：添加二维位置比较点
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定卡上的即将进行位置比较的轴列表(两个轴)</param>
        /// <param name="pos">二维位置比较位置列表，单位：pulse</param>
        /// <param name="dir">比较模式列表，0：小于等于，1：大于等于</param>
        /// <param name="action">二维位置比较点触发功能编号</param>
        /// <param name="actpara">二维位置比较点触发功能参数</param>
        /// <returns>错误代码</returns>
        int AddCardComparePointExtern(int CardNo, ushort[] axis, int[] pos, ushort[] dir, ushort action, int actpara);

        /// <summary>
        /// 二维低速位置比较：读取当前二维位置比较点位置
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="pos">返回当前二维位置比较点位置</param>
        /// <returns>错误代码</returns>
        int GetCardCompareCurrentPointExtern(int CardNo, ref int[] pos);

        /// <summary>
        /// 二维低速位置比较：查询已经比较过的二维比较点个数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="pointNum">返回已经比较过的二维位置比较点数</param>
        /// <returns>错误代码</returns>
        int GetCardComparePointsRunnedExtern(int CardNo, ref int pointNum);

        /// <summary>
        /// 二维低速位置比较：查询可以加入的二维比较点个数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="pointNum">返回可以加入的二维位置比较点数</param>
        /// <returns>错误代码</returns>
        int GetCardComparePointsRemainedExtern(int CardNo, ref int pointNum);

        #endregion


        #region 高速单次位置锁存、高速连续位置锁存
        /// <summary>
        /// 根据锁存器的锁存号获取锁存状态和锁存值
        /// </summary>
        /// <param name="latchParam"></param>
        /// <returns></returns>
        MultiplexedLatchParam GetCradMultiplexedLatchStatus(MultiplexedLatchParam latchParam);
        /// <summary>
        /// 给对应的锁存器设置参数
        /// </summary>
        /// <param name="latchParam"></param>
        /// <returns></returns>
        int SetMultiAxisMode(MultiplexedLatchParam latchParam);
        /// <summary>
        /// 打开锁存器
        /// </summary>
        /// <param name="latchParam"></param>
        /// <returns></returns>
        int OpenCardMultiLtc(MultiplexedLatchParam latchParam);
        /// <summary>
        /// 复位锁存器;先执行清除锁存器,然后关闭锁存器操作
        /// </summary>
        /// <param name="latchParam"></param>
        /// <returns></returns>
        int CardResetLatch(MultiplexedLatchParam latchParam);
        /// <summary>
        /// 高速单次位置锁存：设置指定轴的 LTC 信号
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00：0~7，DMC3800：0~7，DMC3600：0~5 DMC3400A：0~3</param>
        /// <param name="ltc_logic">LTC 信号的触发方式，0：下降沿锁存，1：上升沿锁存，2：双边沿锁存</param>
        /// <param name="ltc_mode">保留参数，固定值为 0</param>
        /// <param name="filter">保留参数，固定值为 0</param>
        /// <returns>错误代码</returns>
        int SetCardAxisLtcMode(int CardNo, int axis, ushort ltc_logic, ushort ltc_mode, double filter);

        /// <summary>
        /// 高速单次位置锁存：设置锁存方式
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00：0~7，DMC3800：0~7，DMC3600：0~5 DMC3400A：0~3</param>
        /// <param name="all_enable">锁存方式：0：单次锁存 1：保留 2：连续锁存 3：触发延时急停</param>
        /// <param name="latch_source">锁存源，0：指令位置计数器，1：编码器计数器</param>
        /// <param name="triger_chunnel">保留参数，固定值为 0</param>
        /// <returns>错误代码</returns>
        int SetCardAxisLatchMode(int CardNo, int axis, int all_enable, int latch_source, int triger_chunnel);




        /// <summary>
        /// 高速单次位置锁存：从控制卡内读取指定卡内锁存器的标志位
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <returns>0：未触发锁存，1：已触发锁存</returns>
        int GetCardAxisLatchFlag(int CardNo, int axis);


        /// <summary>
        /// 高速单次位置锁存：复位指定卡的锁存器的标志位
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <returns></returns>
        int GetCardAxisReserLatchFlag(int CardNo, int axis);

        /// <summary>
        /// 高速连续位置锁存：从 PC 缓存中读取锁存器已锁存个数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <returns></returns>
        int GetCardAxisLatchFlagExtern(int CardNo, int axis);

        /// <summary>
        /// 高速单次位置锁存：按索引号读取 PC 缓冲区中已保存的锁存值
        /// <para>注 意：</para><para>当选择锁存方式为连续锁存时，用此函数读取锁存值。索引号按锁存顺序从 0 开始排列（即第一次锁存的位置值存在索引号为 0 处，第二次锁存的位置值存在索引号为 1处，以此类推）</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="Index">索引号</param>
        /// <returns>锁存值</returns>
        int GetCardAxisLatchValueExtern(int CardNo, int axis, int Index);


        /// <summary>
        /// 从控制卡内读取编码器锁存器的值
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <returns>锁存值</returns>
        int GetCardAxisLatchValue(int CardNo, int axis);

        #endregion


        #region LTC触发延时急停

        /// <summary>
        /// 设置 LTC 端口触发延时急停时间
        /// <para>注 意：</para>
        /// <para>：触发延时急停模式只对 0 号轴及 4 号轴起作用；LTC0 对应为 0 号轴，LTC1 对应为 4号轴</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3400A：0，DMC3C00/3800/3600：0、4</param>
        /// <param name="time">触发延时停止时间，单位：us，取值范围：1us~50ms</param>
        /// <returns>错误代码</returns>
        int SetCardAxisLatchStopTime(int CardNo, int axis, int time);

        #endregion


        #region LTC反相输出

        /// <summary>
        /// LTC 反相输出设置
        /// <para>注 意：</para><para>当某输出端口作为 LTC 反相输出后，该端口将不能通过通用 IO 函数设置输出值；</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="enable">使能状态：0：禁止，1：使能</param>
        /// <param name="bitno">通用输出 IO 口号，取值范围：0~15</param>
        /// <returns>错误代码</returns>
        int SetCardAxisOutMode(int CardNo, int axis, int enable, int bitno);

        /// <summary>
        ///  读取 LTC 反相输出设置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5,DMC3400A：0~3</param>
        /// <param name="enable">返回使能状态：0：禁止，1：使能</param>
        /// <param name="bitno">返回设置的通用输出 IO 口号</param>
        /// <returns>错误代码</returns>
        int GetCardAxisOutMode(int CardNo, int axis, ref ushort enable, ref ushort bitno);

        #endregion

        #region I/O计数功能

        /// <summary>
        /// 设置 IO 计数模式
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="bitno">输出端口号,取值范围：0~15</param>
        /// <param name="mode">IO 计数模式，0：禁用，1：上升沿计数，2：下降沿计数</param>
        /// <param name="filter_time">滤波时间，单位：s</param>
        /// <returns>错误代码</returns>
        int SetCardIoCountMode(int CardNo, int bitno, int mode, double filter_time);

        /// <summary>
        /// 设置 IO 计数值
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="bitno">输出端口号,取值范围：0~15</param>
        /// <param name="CountValue">IO 计数值</param>
        /// <returns>错误代码</returns>
        int SetCardIoCountValue(int CardNo, int bitno, int CountValue);

        /// <summary>
        /// 读取 IO 计数值
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="bitno">输出端口号,取值范围：0~15</param>
        /// <param name="CountValue">返回 IO 计数值</param>
        /// <returns>错误代码</returns>
        int GetCardIoCountValue(int CardNo, int bitno, ref uint CountValue);

        #endregion

        #region IO延时翻转

        /// <summary>
        /// IO 输出延时翻转
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="bitno">输出端口号,取值范围：0~15</param>
        /// <param name="reverse_time">延时翻转时间，单位：s</param>
        /// <returns>错误代码</returns>
        int SetCardReverseOutBit(int CardNo, int bitno, int reverse_time);

        #endregion


        #region 原点锁存

        /// <summary>
        /// 原点锁存: 设置原点锁存模式
        /// <para>注意:DMC3C00后四轴不支持原点锁存功能</para>
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="enable">原点锁存使能，0：禁止，1：允许 </param>
        /// <param name="logic">触发方式，0：下降沿，1：上升沿 </param>
        /// <param name="source">位置源选择，0：指令位置计数器，1：编码器计数器 </param>
        /// <returns>错误代码</returns>
        int SetCardAxisHomelatchMode(int CardNo, int axis, ushort enable, ushort logic, ushort source);

        /// <summary>
        /// 原点锁存: 清除原点锁存标志
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <returns>错误代码</returns>
        int ClearCardAxisHomelatchFlag(int CardNo, int axis);

        /// <summary>
        /// 原点锁存: 读取原点锁存标志
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <returns>原点锁存标志，0：未锁存，1：锁存 </returns>
        int GetCardAxisHomelatchFlag(int CardNo, int axis);

        /// <summary>
        /// 原点锁存: 读取原点锁存值 
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <returns>锁存值，单位：pulse </returns>
        int GetCardAxisHomelatchValue(int CardNo, int axis);

        #endregion


        #region 反向间隙补偿

        /// <summary>
        /// 反向间隙补偿: 设置指定轴的反向间隙值
        /// </summary>
        /// <param name="CardNo">控制卡号</param>
        /// <param name="axis">指定轴号，取值范围: 取值范围:MCC400:0~3, MCC800:0~7, MCC1200:0~11, MCC1600:0~15;</param>
        /// <param name="backlash_value">反向间隙值，单位：unit；</param>
        /// <param name="backlash_interval">反向间隔,脉冲/ms 单位;</param>
        /// <param name="backlash_dir">反向间隙补偿值方向；0 反向，1正向;</param>
        /// <returns>错误代码</returns>
        int SetCardAxisSetBacklash(int CardNo, int axis, int backlash_value, int backlash_interval,
           int backlash_dir);

        /// <summary>
        /// 反向间隙补偿: 读取指定轴的反向间隙值设置
        /// </summary>
        /// <param name="CardNo">控制卡号</param>
        /// <param name="axis">指定轴号，取值范围: 取值范围:MCC400:0~3, MCC800:0~7, MCC1200:0~11, MCC1600:0~15;</param>
        /// <param name="backlash_value">返回反向间隙值，单位：unit；</param>
        /// <param name="backlash_interval">返回反向间隔,脉冲/ms 单位;</param>
        /// <param name="backlash_dir">返回反向间隙补偿值方向，0 反向，1正向;</param>
        /// <returns>错误代码</returns>
        int GetCardAxisSetBacklash(int CardNo, int axis, ref int backlash_value,
            ref int backlash_interval, ref int backlash_dir);


        #endregion


        #region 螺距补偿

        /// <summary>
        /// 使能螺距补偿功能
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">轴号</param>
        /// <param name="enable">使能螺距补偿功能，1：使能，0：不使能</param>
        /// <returns></returns>
        int SetCardLeadScrewCompEnable(int CardNo, int axis, int enable);

        /// <summary>
        /// 设置轴的螺距补偿
        /// </summary>
        /// <param name="pcm"></param>
        /// <returns></returns>
        int SetCardLeadScrewCompConfig(PitchCompensationparamModel pcm);


        #endregion

        #region 读取指定轴的停止原因

        /// <summary>
        /// 读取指定轴的停止原因
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="axis">指定轴号, 取值范围：MCC400:0~3，MCC800:0~7，MCC1200:0~11，MCC1600:0~15;</param>
        /// <param name="StopReason">停止原因: 0:正常停止 1:ALM 立即停止 2:ALM 减速停止 3:LTC 外部触发 4:EMG 立即停止 5:正硬限位 6:负硬限位 7:正硬限位减速停止 8:负硬限位减速停止 9:正软限位立即停止 10:负软限位立即停止 11:正软限位减速停止 12:负软限位减速停止 13:命令立即停止 14:命令减速停止 15:其它原因立即停止 16:其它原因减速停止 17:未知原因立即停止 18:未知原因减速停止 19:外部IO 减速停止</param>
        /// <returns></returns>
        int GetCardAxisStopReason(int CardNo, int axis, ref int StopReason);

        #endregion


        #region 跟随运动函数

        /// <summary>
        /// 轴跟随参数设置.(MCC1600)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="slave_axis">跟随轴号</param>
        /// <param name="master_axis">主轴</param>
        /// <param name="followradio">跟随比例</param>
        /// <returns>错误代码</returns>
        int SetCardAxisFollowParameter(int CardNo, int slave_axis, int master_axis,
           double followradio);

        /// <summary>
        /// 读取轴跟随参数.(MCC1600)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="slave_axis">跟随轴号</param>
        /// <param name="master_axis">主轴</param>
        /// <param name="followradio">跟随比例</param>
        /// <returns>错误代码</returns>
        int GetCardAxisFollowParameter(int CardNo, int slave_axis, ref int master_axis,
            ref double followradio);

        /// <summary>
        /// 轴跟随使能.(MCC1600)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="slave_axis">跟随轴号</param>
        /// <param name="enable">使能状态</param>
        /// <returns></returns>
        int SetCardAxisFollowEnable(int CardNo, int slave_axis, int enable);

        /// <summary>
        /// 读取轴跟随状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="slave_axis">跟随轴号</param>
        /// <param name="enable">使能状态</param>
        /// <returns></returns>
        int GetCardAxisFollowEnable(int CardNo, int slave_axis, ref int enable);

        #endregion

        #region 同步运行单轴运动

        /// 同步运行单轴运动
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis_num">轴数</param>
        /// <param name="axis_list">轴号列表数组，最大长度为axis_num</param>
        /// <param name="aim_pos">轴位置列表数组，最大长度为axis_num</param>
        /// <param name="posi_mode">运动模式,0:相对坐标模式,1:绝对坐标模式；</param>
        /// <returns>错误代码</returns>
        int CardAxisPmotionSync(int CardNo, int axis_num, ushort[] axis_list, int[] aim_pos,
            int posi_mode);

        #endregion


        #region 软着陆

        /// <summary>
        /// 单轴运动软着陆功能(MCC1200/MCC1600)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">制定轴号, 取值范围：MCC400:0~3，MCC800:0~7，MCC1200:0~11，MCC1600:0~15;</param>
        /// <param name="midPos">:第一段pmove 终点位置，单位unit;</param>
        /// <param name="targetPos">:第二段pmove 终点位置,单位unit;</param>
        /// <param name="startVel">起始速度，单位 unit/s;</param>
        /// <param name="maxVel">最大速度，单位 unit/s;</param>
        /// <param name="endVel">停止速度，单位 unit/</param>
        /// <param name="tAcc">加速时间,单位秒（S）;</param>
        /// <param name="tDec">减速时间，单位秒（S）;</param>
        /// <param name="posiMode">位置坐标模式：0-相对位置坐标；1-绝对位置坐标；</param>
        /// <returns></returns>
        int CardAxisPmoveSoftLanding(int CardNo, int axis, double midPos, double targetPos,
            double startVel, double maxVel, double endVel,
            double tAcc, double tDec, int posiMode);

        /// <summary>
        /// 指定轴点位运动软着陆
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号,取值范围MCC400:0~3，MCC800:0~7，MCC1200:0~11，MCC1600:0~15;</param>
        /// <param name="aim_pos">第一段终点位置,单位:pulse;</param>
        /// <param name="target_pos">第二段终点位置，单位:pulse;</param>
        /// <param name="acc_time">加速时间,单位:s(最小值为0.001s)</param>
        /// <param name="dec_time">减速时间,单位:s(最小值为0.001s);</param>
        /// <param name="start_vel">起始速度,单位:pulse/s(最大值为2M)</param>
        /// <param name="max_vel">最大速度,单位:pulse/s(最大值为2M);</param>
        /// <param name="mid_vel">中间速度，单位:pulse/s(最大值为2M);</param>
        /// <param name="stop_vel">停止速度,单位:pulse/s(最大值为2M)</param>
        /// <param name="pos_mode">运动模式,0:相对坐标模式,1:绝对坐标模式</param>
        /// <returns></returns>
        int CardAxisPMotionSoftLanding(int CardNo, int axis, double aim_pos,
            double target_pos, double acc_time, double dec_time, double start_vel,
            double max_vel, double mid_vel, double stop_vel, int pos_mode);


        #endregion


        #region 多段插补/连续插补（缓冲区运动）

        /// <summary>
        /// 设置坐标系参数，确立坐标系映射，建立坐标系（MCC轨迹卡S系列）
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="dimension">坐标系的维数，取值范围：[2, 8]；备注：插补坐标系最小维数为2；</param>
        /// <param name="profile">坐标系【x,y,z,u,v,w,c,c1】与物理轴0-最大轴的映射关系。备注：x,y,z,u,v,w,c,c1映射的物理轴号不能相同</param>
        /// <param name="synVelMax">该坐标系的最大合成速度。如果用户在输入插补段的时候所设置的目标速度大于了该速度，则将会被限制为该速度。单位：unit/s。</param>
        /// <param name="synAccMax">该坐标系的最大合成加速度。如果用户在输入插补段的时候所设置的加速度大于了该加速度，则将会被限制为该加速度。单位：unit/s²。</param>
        /// <param name="evenTime">保留值</param>
        /// <param name="setOriginFlag">保留值</param>
        /// <param name="originPos">保留值</param>
        /// <returns>错误代码</returns>
        int SetCardAxisCrdPrm(int CardNo, int crd, ushort dimension, ushort[] profile,
            double synVelMax, double synAccMax, short evenTime, short setOriginFlag, int[] originPos);

        /// <summary>
        /// 查询坐标系参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="dimension">坐标系的维数，取值范围：[2, 8]；备注：插补坐标系最小维数为2；</param>
        /// <param name="profile">坐标系【x,y,z,u,v,w,c,c1】与物理轴0-最大轴的映射关系。备注：x,y,z,u,v,w,c,c1映射的物理轴号不能相同</param>
        /// <param name="synVelMax">该坐标系的最大合成速度。如果用户在输入插补段的时候所设置的目标速度大于了该速度，则将会被限制为该速度。单位：unit/s。</param>
        /// <param name="synAccMax">该坐标系的最大合成加速度。如果用户在输入插补段的时候所设置的加速度大于了该加速度，则将会被限制为该加速度。单位：unit/s²。</param>
        /// <param name="evenTime">保留值</param>
        /// <param name="setOriginFlag">保留值</param>
        /// <param name="originPos">保留值</param>
        /// <returns></returns>
        int GetCardAxisCrdPrm(int CardNo, int crd, ref ushort dimension, ushort[] profile, ref double synVelMax,
           ref double synAccMax, ref short evenTime, ref short setOriginFlag, int[] originPos);

        /// <summary>
        /// 向插补缓存区增加插补数据.用于使用前瞻时向插补缓存区增加插补数据，调用该指令表示后续没有新的数据，将会一次性把前瞻缓存区的数据压入运动缓存区
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号</param>
        /// <returns>错误代码</returns>
        int SetCardAxisBufCrdData(int CardNo, int crd);


        /// <summary>
        /// 直线插补
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="axisNum">插补轴数</param>
        /// <param name="AxisList">轴号列表</param>
        /// <param name="aim_pos">插补终点坐标值，单位：unit；</param>
        /// <param name="posi_mode">位置模式，0：相对模式 ；1：绝对模式；</param>
        /// <param name="synVel">插补段的目标合成速度，单位：unit/s；</param>
        /// <param name="synAcc">插补段的合成加速度，单位：unit/s²；</param>
        /// <param name="velEnd">插补段的终点速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <param name="velStart">插补段的起跳速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义否则该值无效。默认值为0；</param>
        /// <returns>错误代码</returns>
        int CardAxisBufLineData(int CardNo, int Crd, ushort axisNum, ushort[] AxisList,
           double[] aim_pos, short posi_mode, double synVel, double synAcc,
           double velEnd, double velStart);

        /// <summary>
        /// 圆心插补
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="axisNum">插补轴数</param>
        /// <param name="AxisList">轴号列表</param>
        /// <param name="aim_pos">插补终点坐标值，单位：unit；</param>
        /// <param name="cen_pos">圆心坐标单位：unit；</param>
        /// <param name="circleDir">圆弧的旋转方向，0：顺时针圆弧； 1：逆时针圆弧；</param>
        /// <param name="circle_num">圆弧圈数</param>
        /// <param name="posi_mode">位置模式，0：相对模式 ；1：绝对模式</param>
        /// <param name="synVel">插补段的目标合成速度，单位：unit/s</param>
        /// <param name="synAcc">插补段的合成加速度，单位：unit/s²</param>
        /// <param name="velEnd">插补段的终点速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <param name="velStart">插补段的起跳速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <returns>错误代码</returns>
        int CardAxisBufArcnCenterMove(int CardNo, int Crd, ushort axisNum, ushort[] AxisList,
           double[] aim_pos, ref double cen_pos, ushort circleDir, ushort circle_num,
           short posi_mode, double synVel, double synAcc, double velEnd, double velStart);


        /// <summary>
        /// 半径圆弧插补
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="axisNum">插补轴数</param>
        /// <param name="AxisList">轴号列表</param>
        /// <param name="aim_pos">插补终点坐标值，单位：unit；</param>
        /// <param name="radius">圆弧插补的圆弧半径值，单位：unit；半径为正时，表示圆弧为小于等于180°圆弧，半径为负时，表示圆弧为大于180°圆弧；</param>
        /// <param name="circleDir">圆弧的旋转方向，0：顺时针圆弧；1：逆时针圆弧；</param>
        /// <param name="circle_num">圆弧圈数</param>
        /// <param name="posi_mode">位置模式，0：相对模式；1：绝对模式</param>
        /// <param name="synVel">插补段的目标合成速度，单位：unit/s；</param>
        /// <param name="synAcc">插补段的合成加速度，单位：unit/s²；</param>
        /// <param name="velEnd">插补段的终点速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <param name="velStart">插补段的起跳速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <returns>错误代码</returns>
        int CardAxisBufArcnRadiusMove(int CardNo, int Crd, ushort axisNum, ushort[] AxisList,
            double[] aim_pos, double radius, ushort circleDir, ushort circle_num,
            short posi_mode, double synVel, double synAcc, double velEnd, double velStart);


        /// <summary>
        /// 三点圆弧插补
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Crd">坐标系号，取值范围: (MCC400S/MCC800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="axisNum">插补轴数</param>
        /// <param name="AxisList">轴号列表</param>
        /// <param name="aim_pos">插补终点坐标值，单位：unit；</param>
        /// <param name="radius">圆弧插补的圆弧半径值，单位：unit；半径为正时，表示圆弧为小于等于180°圆弧，半径为负时，表示圆弧为大于180°圆弧；</param>
        /// <param name="circleDir">圆弧的旋转方向，0：顺时针圆弧；1：逆时针圆弧；</param>
        /// <param name="circle_num">圆弧圈数</param>
        /// <param name="posi_mode">位置模式，0：相对模式；1：绝对模式</param>
        /// <param name="synVel">插补段的目标合成速度，单位：unit/s；</param>
        /// <param name="synAcc">插补段的合成加速度，单位：unit/s²；</param>
        /// <param name="velEnd">插补段的终点速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <param name="velStart">插补段的起跳速度，单位：unit/s。该值只有在没有使用前瞻预处理功能时才有意义，否则该值无效。默认值为0</param>
        /// <returns>错误代码</returns>
        int CardAxisBufArcn3pointMove(int CardNo, int Crd, ushort axisNum, ushort[] AxisList,
            double[] aim_pos, ref double mid_pos, ushort circle_num, short posi_mode, double synVel,
                double synAcc, double velEnd, double velStart);


        /// <summary>
        /// 缓存区内数字量IO输出设置指令
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">:坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S/MCC1600S:0-2)；</param>
        /// <param name="doType">数字量输出的类型：10：输出驱动器使能；11：输出驱动器报警清除；12：输出通用输出。</param>
        /// <param name="doMask">从bit0-bit15 按位表示指定的数字量输出是否有操作： 0：该路数字量输出无操作；1：该路数字量输出有操作。</param>
        /// <param name="doValue">从bit0-bit15 按位表示指定的数字量输出的值。</param>
        /// <returns>错误代码</returns>
        int CardAxisBufIO(int CardNo, int crd, ushort doType, ushort doMask, ushort doValue);


        /// <summary>
        /// 缓存区指令，缓存区内延时设置指令；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="delayTime">延时时间.单位：ms；</param>
        /// <returns></returns>
        int CardAxisBufDelay(int CardNo, int crd, ushort delayTime);


        /// <summary>
        /// 缓存区指令，缓存区内有效限位开关
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="axis">需要将限位有效的轴的编号，取值范围:MCC400:0~3,MCC800:0~7,MCC1200:0~11,MCC1600:0~15；</param>
        /// <param name="limitType">需要有效的限位类型：0：需要将该轴的正限位设置为有效；1：需要将该轴的负限位设置为有效；-1:需要将该轴的正限位和负限位都设置为有效，默认为该值</param>
        /// <returns>错误代码</returns>
        int CardAxisBufLimitON(int CardNo, int crd, short axis, short limitType);

        /// <summary>
        /// 设置缓存区内无效限位开关
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="axis">需要将限位有效的轴的编号，取值范围:MCC400:0~3,MCC800:0~7,MCC1200:0~11,MCC1600:0~15；</param>
        /// <param name="limitType">需要无效的限位类型；0：需要将该轴的正限位无效；1：需要将该轴的负限位无效；-1：需要将该轴的正限位和负限位都无效，默认为该值。</param>
        /// <returns>错误代码</returns>
        int CardAxisBufLimitOff(int CardNo, int crd, short axis, short limitType);


        /// <summary>
        /// 缓存区内设置axis 的停止IO信息
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="axis">需要停止轴的编号，取值范围:MCC400:0~3,MCC800:0~7,MCC1200:0~11,MCC1600:0~15</param>
        /// <param name="stopType">需要设置停止IO信息的停止类型；0：紧急停止类型；1：平滑停止类型</param>
        /// <param name="inputType">设置的数字量输入的类型；0：正限位；1：负限位；2：驱动报警；3：原点开关；4：通用输入；5：电机到位信号。</param>
        /// <param name="inputIndex">设置的数字量输入的索引号，取值范围根据inputType 的取值而定；当inputType= 0,1,2,4,5时，取值[0,7],当inputType= 4时，取值[1,31]</param>
        /// <returns>错误代码</returns>
        int CardAxisBufSetStopIO(int CardNo, int crd, short axis,
             short stopType, short inputType, short inputIndex);

        /// <summary>
        /// 实现刀向跟随功能，启动某个轴点位运动
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="moveAxis">需要进行点位运动的轴号，取值范围：[0, 7];该轴不能处于坐标系中；</param>
        /// <param name="pos">点位运动的目标位置，单位：unit；</param>
        /// <param name="vel">点位运动的目标速度，单位：unit/s</param>
        /// <param name="acc_time">点位运动的加减速时间，单位：s；</param>
        /// <returns>错误代码</returns>
        int CardAxisBufMove(int CardNo, int crd, short moveAxis, double pos, double vel, double acc_time);

        /// <summary>
        /// 查询插补缓存区剩余空间
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pSpace">读取插补缓存区中的剩余空间；最大为4096段</param>
        /// <returns>错误代码</returns>
        int CardAxisBufCrdRemainSpace(int CardNo, int crd, ref int pSpace);

        /// <summary>
        /// 清除插补缓存区内的插补数据
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <returns></returns>
        int CardAxisBufCrdClear(int CardNo, int crd);

        /// <summary>
        /// 启动缓冲区插补运动
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <returns></returns>
        int CardAxisBufCrdStart(int CardNo, int crd);

        /// <summary>
        /// 暂停缓冲区插补运动。在暂停缓冲区插补运动后，通过调用函数YK_buf_crd_start进行重新启动。
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <returns></returns>
        int CardAxisBufCrdPause(int CardNo, int crd);

        /// <summary>
        /// 停止缓冲区插补运动
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="mode">停止模式；0：减速停止；1：立即停止；</param>
        /// <returns></returns>
        int CardAxisBufCrdStop(int CardNo, int crd, int mode);

        /// <summary>
        /// 查询插补运动坐标系状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pRun">读取插补运动状态：0：运行状态；1：停止状态；2：暂停状态 3：激活状态 4：空闲状态  5：错误状态</param>
        /// <param name="pSegment">读取当前已经完成的插补段数。当重新建立坐标系或者调用MCC_CrdClear 指令后，该值会被清零</param>
        /// <returns>错误代码</returns>
        int CardAxisBufCrdStatus(int CardNo, int crd, ref short pRun, ref int pSegment);

        /// <summary>
        /// 设置自定义插补段段号。控制卡默认的自定义段号为1，之后每增加一个指令，就自动增加一。如果用户自己设定，则需要对每一条指令都指定相应的段号；使用YK_buf_get_user_seg_num可读回设置的相应段号。
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="segNum">设置用户自定义的插补段段号</param>
        /// <returns></returns>
        int SetCardAxisBufUserSegNum(int CardNo, int crd, long segNum);

        /// <summary>
        /// 读取自定义插补段段号
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="segNum">读取的用户自定义的插补段段号</param>
        /// <returns></returns>
        int GetCardAxisBufUserSegNum(int CardNo, int crd, ref long segNum);

        /// <summary>
        /// 读取未完成的插补段段数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pSegment">读取的剩余插补段的段数</param>
        /// <returns></returns>
        int GetCardAxisBufRemainSegNum(int CardNo, int crd, ref long pSegment);

        /// <summary>
        /// 设置插补运动目标合成速度倍率
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="synVelRatio">设置的插补目标速度倍率，取值范围：(0, 1]，系统默认该值为1；</param>
        /// <returns>错误代码</returns>
        int SetCardAxisBufSetOverride(int CardNo, int crd, double synVelRatio);

        /// <summary>
        /// 设置插补运动平滑停止、急停合成加速度
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="decSmoothStop">设置的坐标系合成平滑停止加速度，单位：unit/ s²；</param>
        /// <param name="decAbruptStop">设设置的坐标系合成急停加速度，单位：unit/ s²；</param>
        /// <returns>错误代码</returns>
        int SetCardAxisBufSetCrdStopDec(int CardNo, int crd, double decSmoothStop, double decAbruptStop);

        /// <summary>
        /// 查询插补运动平滑停止、急停合成加速度
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="decSmoothStop">查询坐标系合成平滑停止加速度，单位：unit/ s²；</param>
        /// <param name="decAbruptStop"> 查询坐标系合成急停加速度，单位：unit/ s²；</param>
        /// <returns></returns>
        int GetCardAxisBufSetCrdStopDec(int CardNo, int crd, ref double decSmoothStop, ref double decAbruptStop);


        /// <summary>
        /// 查询该坐标系的当前坐标位置值
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pPos">读取的坐标系的坐标值，单位：unit。该参数为一个数组首元素的指针，数组的元素个数取决于该坐标系的维数；</param>
        /// <returns>错误代码</returns>
        int GetCardAxisBufGetCrdPos(int CardNo, int crd, ref double pPos);


        /// <summary>
        /// 查询该坐标系的当前坐标速度值
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pSynVel">读取的坐标系的合成速度值, 单位：unit/s；</param>
        /// <returns>错误代码</returns>
        int GetCardAxisBufGetCrdVel(int CardNo, int crd, ref double pSynVel);

        /// <summary>
        /// 初始化插补前瞻缓存区
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="T">轨迹误差控制参数。当T属于[0,50]，表示拐弯轨迹百分比；当T等于零表示轨迹没有过渡；当T小于零，表示轨迹误差；</param>
        /// <param name="accMax">最大加速度，单位：unit/ s²；</param>
        /// <param name="enable">前瞻使能标志。0:前瞻禁止； 1:前瞻使能；</param>
        /// <returns>错误代码</returns>
        int CardAxisBufInitLookahead(int CardNo, int crd, double T, double accMax, int enable);

        /// <summary>
        /// 查询插补前瞻缓存区
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="T">轨迹误差控制参数。当T属于[0,50]，表示拐弯轨迹百分比；当T等于零表示轨迹没有过渡；当T小于零，表示轨迹误差；</param>
        /// <param name="accMax">最大加速度,单位：unit/ s²。</param>
        /// <param name="enable">前瞻使能标志, 0:前瞻禁止； 1:前瞻使能；</param>
        /// <returns>错误代码</returns>
        int GetCardAxisBufInitLookahead(int CardNo, int crd, ref double T,
            ref double accMax, ref int enable);


        /// <summary>
        ///  设置插补速度曲线平滑系数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="Smooth">插补速度曲线平滑系数，范围[0,1]</param>
        /// <returns>错误代码</returns>
        int SetCardAxisBufCrdSmooth(int CardNo, int crd, double Smooth);

        /// <summary>
        /// 查询插补速度曲线平滑系数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="Smooth">插补速度曲线平滑系数，范围[0,1]</param>
        /// <returns>错误代码</returns>
        int GetCardAxisBufCrdSmooth(int CardNo, int crd, ref double Smooth);

        /// <summary>
        /// 关闭坐标系
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <returns>错误代码</returns>
        int CardAxisBufCrdReset(int CardNo, int crd);

        /// <summary>
        /// 缓存区等待通用输入IO指令
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="dI_id">通用输入IO口序号</param>
        /// <param name="di_logic">需要等待的通用输入IO口电平</param>
        /// <param name="time_out">等待最大时间，单位 毫秒（ms）</param>
        /// <returns></returns>
        int CardAxisBufWaitDI(int CardNo, int crd, ushort dI_id, ushort di_logic, long time_out);


        /// <summary>
        /// 连续插补缓冲区中PWM 输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pwm_no">PWM 通道，取值范围：0-1；</param>
        /// <param name="pwm_duty">占空比，取值范围：0-1；</param>
        /// <param name="pwm_freq">频率，取值范围：0-2MHz；</param>
        /// <returns></returns>
        int CardAxisBufPwmOutput(int CardNo, int crd, ushort pwm_no, double pwm_duty,
            double pwm_freq);

        /// <summary>
        /// 连续插补缓冲区中PWM 跟随
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="pwm_no">PWM 通道，取值范围：0-1；</param>
        /// <param name="mode">跟随模式：1：占空比跟随；2：频率跟随；</param>
        /// <param name="start_speed">开始跟随速度, 单位：unit/s；</param>
        /// <param name="max_speed">最大跟随速度，单位：unit/s；</param>
        /// <param name="max_power">最大跟随能量(频率或占空比)：跟随模式为1时：占空比，取值范围：0-1；跟随模式为2时：频率，取值范围：0-2MHz。</param>
        /// <param name="min_power">最小跟随能量(频率或占空比)：跟随模式为1时：占空比，取值范围：0-1；跟随模式为2时：频率，取值范围：0-2MHz；</param>
        /// <param name="none_follow_value">非跟随值(频率或占空比)：跟随模式为1时：占空比，取值范围：0-1；跟随模式为2时：频率，取值范围：0-2MHz；</param>
        /// <returns></returns>
        int CardAxisBufPwmFollow(int CardNo, int crd, ushort pwm_no, ushort mode,
            double start_speed, double max_speed, double max_power,
            double min_power, double none_follow_value);

        /// <summary>
        /// 连续插补中相对于轨迹段起点IO 滞后输出（段内执行）
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="bitno">输出口号，取值范围：0-31;</param>
        /// <param name="on_off">电平状态，0：低电平，1：高电平;</param>
        /// <param name="delay_value">滞后值，单位：s（滞后时间模式）或 unit（滞后距离模式）;</param>
        /// <param name="delay_mode">滞后模式，：滞后时间，：滞后距离;</param>
        /// <param name="ReverseTime">电平输出后的延时翻转时间，单位：s;</param>
        /// <returns></returns>
        int CardAxisBufDelayOutbitToStartPos(int CardNo, int crd, int bitno, int on_off,
            double delay_value, int delay_mode, double ReverseTime);

        /// <summary>
        /// 连续插补中相对于轨迹段终点IO 滞后输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="bitno">输出口号，取值范围：0-31;</param>
        /// <param name="on_off">电平状态，0:低电平，1:高电平;</param>
        /// <param name="delay_time">滞后时间，单位：秒（s）;</param>
        /// <param name="ReverseTime">保留参数，固定值为0;</param>
        /// <returns></returns>
        int CardAxisBufDelayOutbitToStopPos(int CardNo, int crd, int bitno,
            int on_off, double delay_time, double ReverseTime);

        /// <summary>
        /// 连续插补中相对于轨迹段终点IO 提前输出（段内执行）
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="bitno">输出口号，取值范围:0~31</param>
        /// <param name="on_off">电平状态 ，0：低电平，1：高电平；</param>
        /// <param name="ahead_value">提前值，单位：s（提前时间模式）或 unit（提前距离模式）；</param>
        /// <param name="ahead_mode">提前模式，：0提前时间，1：提前距离；</param>
        /// <param name="ReverseTime">电平输出后的延时翻转时间，单位：s；</param>
        /// <returns></returns>
        int CardAxisBufAheadOutbitToStopPos(int CardNo, int crd, int bitno,
            int on_off, double ahead_value, int ahead_mode, double ReverseTime);


        /// <summary>
        /// 打开缓冲区PWM 开关
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="PwmNo">PWM 通道，取值范围：[0,1]</param>
        /// <returns></returns>
        int CardAxisBufSetPwmON(int CardNo, int crd, int PwmNo);


        /// <summary>
        /// 关闭缓冲区PWM 开关
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">坐标系号，取值范围: (MCC400S/800S:取值范围:0-1;MCC1200S:0-2)；</param>
        /// <param name="PwmNo">PWM 通道，取值范围：0-1；</param>
        /// <returns></returns>
        int CardAxisBufSetPwmOFF(int CardNo, int crd, int PwmNo);


        #endregion


        #region Localcat IO(1600P专用)

        /// <summary>
        /// 获取拓展板的AD/DA输入输出口数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="TotalIn">Localbus总线AD输入数；</param>
        /// <param name="TotalOut">Localbus总线DA输出数；</param>
        /// <returns>错误代码</returns>
        int CardAxisGetLocalcatTotalAdcnum(int CardNo, ref int TotalIn, ref int TotalOut);


        /// <summary>
        /// 获取拓展板的总线IO输入输出口数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="TotalIn">Localbus总线AD输入数；</param>
        /// <param name="TotalOut">Localbus总线DA输出数；</param>
        /// <returns>错误代码</returns>
        int CardAxisGetLocalcatTotalIonum(int CardNo, ref int TotalIn, ref int TotalOut);


        /// <summary>
        /// 设置拓展的拓展板DA参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA输出口号，取值范围0-1</param>
        /// <param name="Value">DA输出值</param>
        /// <returns>错误代码</returns>
        int CardAxisYKSetLocalcatDaOutput(int CardNo, int channel, short Value);


        /// <summary>
        /// 读取拓展板DA参数；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA输出口号，取值范围0-1；</param>
        /// <param name="Value">DA输出值；</param>
        /// <returns></returns>
        int CardAxisGetLocalcatDaOutput(int CardNo, int channel, ref short Value);


        /// <summary>
        /// 读取拓展板AD参数；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA 输入口号，取值范围0-1；</param>
        /// <param name="Value">返回AD参数值；</param>
        /// <returns></returns>
        int CardAxisGetLocalcatAdInput(int CardNo, int channel, ref short Value);


        /// <summary>
        /// 配置拓展板AD模式；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">AD 输入口号，取值范围0-1；</param>
        /// <param name="mode">模式0: 0V~10V 1: -10V~10V 2: 0V~5V 3: -5V~5V 4:1V~5V ;</param>
        /// <returns>错误代码</returns>
        int CardAxisSetLocalcatAdMode(int CardNo, int channel, int mode);


        /// <summary>
        /// 读取拓展板AD模式配置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">AD 输入口号，取值范围0-1；</param>
        /// <param name="mode">返回模式0 : 0V~10V 1 : -10V~10V 2 : 0V~5V 3 : -5V~5V 4 : 1V~5V;</param>
        /// <returns>错误代码</returns>
        int CardAxisGetLocalcatAdMode(int CardNo, int channel, ref int mode);


        /// <summary>
        /// 配置拓展板DA模式；
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA 输入口号，取值范围0-1；</param>
        /// <param name="mode">模式0: 0V~10V 1: -10V~10V 2: 0V~5V 3: -5V~5V 4:1V~5V ;</param>
        /// <returns></returns>
        int CardAxisSetLocalcatDaMode(int CardNo, int channel, int mode);




        /// <summary>
        /// 读取拓展板AD模式配置
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="channel">DA 输入口号，取值范围0-1；</param>
        /// <param name="mode"> 返回模式0 : 0V~10V 1 : -10V~10V 2 : 0V~5V 3 : -5V~5V 4 : 1V~5V;</param>
        /// <returns>错误代码</returns>
        int CardAxisGetLocalcatDaMode(int CardNo, int channel, ref int mode);


        /// <summary>
        /// 获取错误码函数
        /// </summary>
        /// <param name="CardNo"> 控制卡卡号，取值范围0-7；</param>
        /// <param name="LocalcatNo">Localcat模组号，默认为0；</param>
        /// <param name="ErrCode">返回Localcat模组号的数据通讯错误码；</param>
        /// <returns></returns>
        int CardAxisLocalcatGetErrCode(int CardNo, int LocalcatNo, ref int ErrCode);


        #endregion



        //public int SetCardHcmpEnable(int CardNo, int axis, int hcmp, int cmp_mode = 0)

        /// <summary>
        /// 设置指定轴的 INP 信号
        /// <para>注意：</para>
        /// <para>当使能 INP 信号功能后，只有在 INP 信号为有效状态时，对应的轴才能进行运动，否则此时检测轴的状态是正在运行（即对轴运动作限制）</para> 
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00：0~11，DMC3800：0~7，DMC3600：0~5 DMC3400A：0~3</param>
        /// <param name="enable">INP 信号使能，0：禁止，1：允许</param>
        /// <param name="inp_logic">INP 信号的有效电平，0：低有效，1：高有效</param>
        /// <returns>错误代码</returns>
        int SetCardAxisInpMode(int CardNo, int axis, int enable, int inp_logic);

        /// <summary>
        /// 读取当前速度值 
        /// <para>注意：</para>
        /// <para>当执行直线插补运动时，该函数读取的速度为矢量速度；当执行圆弧插补运动时，该函数读取的速度为各轴分量速度</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <returns>指定轴的速度，单位：pulse/s</returns>
        double GetCardAxisCurrentSpeed(int CardNo, int axis);




        /// <summary>
        /// 启动转盘分拣比较输出
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="GroupNo">组号，只能取值1或者2</param>
        /// <returns></returns>
        int CardAxisStartSelectHcmp(ushort CardNo, int camera_count, ushort GroupNo = 1);


        /// <summary>
        /// 停止转盘分拣比较输出
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="GroupNo">组号，只能取值1或者2</param>
        /// <returns></returns>
        int CardAxisStopSelectHcmp(ushort CardNo, ushort GroupNo = 1);

        /// <summary>
        ///  转盘分拣比较输出:添加相机触发io索引
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="hcmp">分组，取1或者2</param>
        /// <param name="ioIndex"></param>
        /// <param name="GroupNo"></param>
        /// <returns></returns>
        int AddCCDTriIO(int CardNo, int hcmp, short ioIndex);



        /// <summary>
        ///设置插补运动速度曲线的平滑时间,此api仅用于e3032卡
        /// </summary>
        /// <param name="CardNo">卡号 </param>
        /// <param name="Crd">坐标系号，取值范围：0~5 </param>
        /// <param name="s_mode">保留参数，固定值为 0</param>
        /// <param name="s_para">平滑时间，单位：s，范围：0~1</param>
        /// <returns>错误代码</returns>
        int DmcSetCardVectorSProfile(int CardNo, int Crd, int s_mode, double s_para);

        /// <summary>
        /// 获取单轴运动速度曲线  
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="Min_Vel">返回起始速度，单位：pulse/s (最大值为 2M)</param>
        /// <param name="Max_Vel">返回最大速度，单位：pulse/s (最大值为 2M)</param>
        /// <param name="Tacc">返回加速时间，单位：s (最小值为 0.001s)</param>
        /// <param name="Tdec">返回减速时间，单位：s (最小值为 0.001s)</param>
        /// <param name="stop_vel">返回停止速度，单位：pulse/s (最大值为 2M)</param>
        /// <returns>：错误代码</returns>
        int GetCardAxisProfile(int CardNo, int axis, ref double Min_Vel, ref double Max_Vel, ref double Tacc, ref double Tdec, ref double stop_vel);

        /// <summary>
        /// 设置单轴速度曲线 S 段参数值
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00/3800：0~7，DMC3600：0~5 DMC3400A：0~3 </param>
        /// <param name="s_mode">保留参数，固定值为 0</param>
        /// <param name="s_para">返回设置的 S 段时间，单位：s；范围：0~0.5 s</param>
        /// <returns>错误代码</returns>
        int GetCardAxisSProfile(int CardNo, int axis, int s_mode, ref double s_para);



        /// <summary>
        /// 总线卡时，取总线错误
        /// </summary>
        /// <param name="ErrNum"></param>
        /// <returns></returns>
        string GetEtherCATErrorInfo(int ErrNum);

        /// <summary>
        /// 打开位置比较输出
        /// </summary>
        /// <returns></returns>
        int OpenCardCompareConfig(int CardNo, int axis, int enable, int cmp_source);

        /// <summary>
        /// 轴所属卡的名字。
        /// </summary>
        string AxisWhichCardName { get; set; }

        /// <summary>
        /// 轴所属卡的类型（有些系列卡，可以用此属性区分具体是哪一种卡）
        /// </summary>
        string AxisWhichcardType { get; set; } 

        /// <summary>
        /// 轴所属的卡号（在多卡的时候轴所属的卡号就不再是0了）
        /// </summary>
        int AxisWhichCardNo { get; set; }

        /// <summary>
        /// 轴名字
        /// </summary>
        string AxisName { get; set; }

        /// <summary>
        /// 轴标签
        /// </summary>
        string AxisNotes { get; set; }

        /// <summary>
        /// 这个轴功能的注释
        /// </summary>
        string AxisNotes2 { get; set; }

        /// <summary>
        /// 轴ID，用于控制卡SDK函数识别运动轴号
        /// </summary>
        int AxisID { get; set; }

        /// <summary>
        /// 轴的运动方式状态
        /// </summary>
        MotionParamModel AxisMotionStatus { get; set; }

        /// <summary>
        /// 虚拟卡(当用户勾选虚拟卡后，轴对象这里需要知道当前是虚拟卡)
        /// </summary>
        bool IsVitualCard { get; set; }

        /// <summary>
        /// 轴状态, 0轴停止,1轴运行中
        /// </summary>
        int AxisStatus { get; set; }

        /// <summary>
        /// 正极限信号，1表示正限位有效， 0表示无效
        /// </summary>
        int AxisPEL { get; set; }
        /// <summary>
        /// 负极限信号，1表示负限位有效， 0表示无效
        /// </summary>
        int AxisMEL { get; set; }
        /// <summary>
        /// 原点信号，1表示原点有效， 0表示无效
        /// </summary>
        int AxisORG { get; set; }
        /// <summary>
        /// Index信号，1表示EZ为高电平， 0表示为低电平
        /// </summary>
        int AxisEZ { get; set; }
        /// <summary>
        /// EMG信号，1表示EMG输入为高， 0表示输入为低；该信号为低电平有效。
        /// </summary>
        int AxisEMG { get; set; }

        /// <summary>
        /// 报警信号, 1为报警  
        /// </summary>
        int AxisAlarm { get; set; }

        /// <summary>
        /// 是否允许编码器
        /// </summary>
        bool EncodeEnable { get; set; }

        /// <summary>
        /// 用户定义的运动目标位置
        /// </summary>
        double TargetPos { get; set; }

        /// <summary>
        /// 用户定义的运动目标位置
        /// </summary>
        double TargetVel { get; set; }

        /// <summary>
        /// 回原标志--上电默认标志为false，伺服必须进行一次复位
        /// </summary>
        bool HomeFlag { get; set; }
        
        /// <summary>
        /// 轴是否在线
        /// </summary>
        bool Online { get; set; }

        CAxisParameter AxisParameter { get; set; }

        /// <summary>
        /// 设置回零遇限位是否反找。（DMC3C00，3400A 默认使能，DMC3800，3600 默认不使能）
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <param name="enable"></param>
        /// <returns></returns>
        int SetCardAxisHomeElReturn(int CardNo, int axis, ushort enable);



        /// <summary>
        /// 获取坐标系的运动状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="crd">指定控制卡上的坐标系号（取值范围：0~1）</param>
        /// <returns>：坐标系状态，0：正在使用中，1：正常停止</returns>
        int GetCardCheckDoneMulticoor(int CardNo, int crd);

        /// <summary>
        /// 停止坐标系内所有轴的运动
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="crd"></param>
        /// <param name="stop_mode"></param>
        /// <returns></returns>
        int CardAxisStopMulticoor(int CardNo, int crd, int stop_mode);


        /// <summary>
        /// 函数调用打印输出设置
        /// <para>注 意：</para>
        /// <para>使能打印输出后，可监控运动函数库的调用情况。在用户调用函数时，将输出相关信息，并保存在指定文件路径中；函数设置模式 2 全部不打印需配合最新动态库（20181030 及以后动态库）使用。</para>
        /// </summary>
        /// <param name="CardNo">打印输出模式，0：只打印报错函数，1：全部打印，2：全部不打印</param>
        /// <param name="FileName">文件保存路径：参数文件名+后缀：相对路径 ；完整描述参数文件的路径+文件名后缀：绝对路径</param>
        /// <returns>错误代码</returns>
        int SetCardDebugMode(int CardNo, string FileName);

        /// <summary>
        /// 读取指定轴的伺服使能端口的电平
        /// </summary>
        /// <returns>伺服使能端口电平，0：低电平(on)，1：高电平(off)</returns>
        int GetCardAxisSevonPin();


        /// <summary>
        /// 控制指定轴的伺服使能端口的输出
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">指定轴号，取值范围：DMC3C00：0~11，DMC3800：0~7，DMC3600：0~5 DMC3400A：0~3</param>
        /// <param name="on_off">设置伺服使能端口电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        int CardAxisWriteSevonPin(int on_off);


        /// <summary>
        /// 取SDK函数返回的字符串错误信息
        /// </summary>
        /// <param name="ErrNum"></param>
        /// <returns></returns>
        string GetErrorInfo(int ErrNum);


        /// <summary>
        ///  设置编码器位置
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <param name="encoder_value"></param>
        int SetCardAxisEncoder(int CardNo, int axis, int encoder_value);

        /// <summary>
        /// 设置轴回零的参数
        /// </summary>
        int SetCardAxisHomeProfile(HomeParameModel hpm);

        /// <summary>
        /// 设置回零模式
        /// LTDMC.dmc_set_homemode((ushort)CardNo, (ushort)axis, (ushort)home_dir, vel, (ushort)mode, (ushort)EZ_count);
        /// </summary>
        int SetCardAxisHomeMode(HomeParameModel hpm);

        /// <summary>
        /// 设置软限位
        /// </summary>
        int SetCardAxisSoftLimit(LimitParamModel lpm);

        /// <summary>
        /// 设置轴的硬限位
        /// </summary>
        /// <returns></returns>
        int SetCardAxisELLimit(LimitParamModel lpm);

        /// <summary>
        /// 设置轴初始速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInitVel();

        /// <summary>
        /// 设置轴的最大速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisMaxVel();

        /// <summary>
        /// 设置轴的加速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisAccVel();

        /// <summary>
        /// 设置单轴运动速度
        /// </summary>
        /// <param name="mpm">运动参数模型
        /// <para>"CardNo"卡号</para>
        /// <para>"axis"指定轴号</para>
        /// <para>"Min_Vel"起始速度，单位：unit/s</para>
        /// <para>"Max_Vel"最大速度，单位：unit/s</para>
        /// <para>"Tacc"加速时间，单位：s</para>
        /// <para>"Tdec"减速时间，单位：s</para>
        /// <para>"Stop_Vel">停止速度，单位：unit/s</para></param>
        /// <returns>错误代码</returns>
        int SetCardAxisMotionalVel(MotionParamModel mpm);

        /// <summary>
        /// 设置轴的加加速
        /// </summary>
        /// <returns></returns>
        int SetCardAxisJerkVel();

        /// <summary>
        /// 设置轴的减减速
        /// </summary>
        /// <returns></returns>
        int SetCardAxisSlowVel();

        /// <summary>
        /// 设置轴的高速回零速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisHighHomeVel();

        /// <summary>
        /// 设置轴的高速回零加速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisHighHomeAccVel();

        /// <summary>
        /// 设置轴的高速回零减速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisHighHomeDecVel();

        /// <summary>
        /// 设置轴的低速回零速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisLowHomeVel();

        /// <summary>
        /// 设置轴的低速回零加速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisLowHomeAccVel();

        /// <summary>
        /// 设置轴的低速回零减速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisLowHomeDecVel();

        /// <summary>
        /// 设置轴的回零位置偏差
        /// </summary>
        /// <returns></returns>
        int SetCardAxisHomePositionErro();

        /// <summary>
        /// 设置轴的反向回零距离
        /// </summary>
        /// <returns></returns>
        int SetCardAxisReverseHomeDis();

        /// <summary>
        /// 设置轴的回零最大保护距离
        /// </summary>
        /// <returns></returns>
        int SetCardAxisHomeMaxProtectDis();

        /// <summary>
        /// 设置轴的当前位置
        /// </summary>
        /// <returns></returns>
        int SetCardAxisCurrentPosition(int CardNo, int axis, int pos);

        /// <summary>
        /// 读取轴回零的参数
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <param name="home_mode"></param>
        /// <param name="Low_Vel"></param>
        /// <param name="High_Vel"></param>
        /// <param name="Tacc"></param>
        /// <param name="Tdec"></param>
        /// <param name="offsetpos"></param>
        /// <returns></returns>
        int GetCardAxisHomeProfile();

        /// <summary>
        /// 读取轴回零的模式
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <param name="home_dir"></param>
        /// <param name="vel"></param>
        /// <param name="mode"></param>
        /// <param name="EZ_count"></param>
        /// <returns></returns>
        int GetCardAxisHomeMode();

        /// <summary>
        /// 获取轴的硬限位
        /// </summary>
        /// <returns></returns>
        int GetCardAxisELLimit();

        /// <summary>
        /// 读取轴的软限位设置
        /// </summary>
        /// <returns>限位参数模型</returns>
        LimitParamModel GetCardAxisSoftLimit(LimitParamModel lpm);

        /// <summary>
        /// 读取轴的初速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisInitVel(/*int CardNo, int Axis,*/ ref int pSpeed);
        /// <summary>
        /// 读取轴的最大速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisMaxVel();



        /// <summary>
        /// 设置轴的减速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisDecVel();

        /// <summary>
        /// 设置轴的加加速
        /// </summary>
        /// <returns></returns>
        int GetCardAxisJerkVel();

        /// <summary>
        /// 设置轴的减减速
        /// </summary>
        /// <returns></returns>
        int GetCardAxisSlowVel();

        /// <summary>
        /// 读取轴的高速回零速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisHighHomeVel();

        /// <summary>
        /// 读取轴的高速回零加速度
        /// </summary>
        /// <returns></returns>
        HomeParameModel GetCardAxisHighHomeProfile(HomeParameModel hpm);

        /// <summary>
        /// 读取轴的高速回零减速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisHighHomeDecVel();

        /// <summary>
        /// 读取轴的低速回零速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisLowHomeVel();

        /// <summary>
        /// 读取轴的低速回零加速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisLowHomeAccVel();

        /// <summary>
        /// 读取轴的低速回零减速度
        /// </summary>
        /// <returns></returns>
        int GetCardAxisLowHomeDecVel();

        /// <summary>
        /// 读取轴的回零位置偏差
        /// </summary>
        /// <returns></returns>
        int GetCardAxisHomePositionErro();

        /// <summary>
        /// 读取轴的反向回零距离
        /// </summary>
        /// <returns></returns>
        int GetCardAxisReverseHomeDis();

        /// <summary>
        /// 读取轴的回零最大保护距离
        /// </summary>
        /// <returns></returns>
        int GetCardAxisHomeMaxProtectDis();

        /// <summary>
        /// 读取轴的当前位置
        /// </summary>
        /// <param name="cntr_no">出脉冲计数器/编码器反馈脉冲位置计数器选择:  0: 输出脉冲计数器 |  1: 编码器反馈脉冲位置计数器</param>
        /// <returns>-1返回错误，返回大于0的值为轴的当前位置</returns>
        double GetCardAxisCurrentPosition(int cntr_no /*, int axis*/);

        /// <summary>
        /// 读取轴状态,停止还是运行中
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">轴号</param>
        /// <returns>轴状态
        /// </returns>
        int GetCardAxisCurrentState(/*int CardNo, int axis*/);

        /// <summary>
        /// 读取卡的当前状态(如果是总线卡，则读总线状态） 
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="channel">对于总线卡，此值固定为2</param>
        /// <returns></returns>
        int GetCardCurrentState(int CardNo, int channel);

        /// <summary>
        /// 读取轴相关的IO的状态。包括正负限位、原点、报警等轴相关IO信号。注意此api名字可能会误以为只是读报警状态，这只是历史问题。
        /// </summary>
        int GetCardAxisAlarmState(int CardNo, int axis);

        /// <summary>
        /// 读取轴的限位状态
        /// </summary>
        /// <returns></returns>
        int GetCardAxisLimitState();

        /// <summary>
        /// 清除轴的报警状态
        /// </summary>
        /// <returns></returns>
        int ClearCardAxisAlarmState(int CardNo, int axis);

        /// <summary>
        /// 打开轴的使能
        /// </summary>
        /// <returns></returns>
        int OpenCardAxisEnable(int CardNo, int axis);

        /// <summary>
        /// 设置 EtherCAT 总线驱动器失能
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">EtherCAT 总线轴的轴号，255 表示使能所有 EtherCAT 轴</param>
        /// <returns>错误代码</returns>
        int SetCardAxisDisable(int CardNo, int axis);

        /// <summary>
        /// 设置轴的运行模式
        /// </summary>
        /// <returns></returns>
        int SetCardAxisRunMode(int CardNo, int axis, ushort runmode);

        /// <summary>
        /// 获取轴当前的运行模式
        /// </summary>
        /// <returns></returns>
        int GetCardAxisRunMode(int CardNo, int axis);

        /// <summary>
        /// 设置轴的脉冲当量
        /// </summary>
        /// <returns></returns>
        int SetCardAxisPulseEquival(int CardNo, int axis, int equiv);

        /// <summary>
        /// 获取轴的脉冲当量
        /// </summary>
        /// <returns></returns>
        int GetCardAxisPulseEquival(int CardNo, int axis);

        /// <summary>
        /// 设置轴的S速度模式
        /// </summary>
        /// <returns></returns>
        int SetCardAxisSProfile(MotionParamModel mpm);

        /// <summary>
        /// 设置轴的T速度模式
        /// </summary>
        /// <returns></returns>
        int SetCardAxisTProfile(MotionParamModel mpm);

        /// <summary>
        /// 驱动指定的轴回零，并立即返回。 回零是否完成，可以通过 p9014_motion_done 查询状态来完成。
        /// </summary>
        /// <returns></returns>
        int CardAxisHomeMove();


        /// <summary>
        /// 读取回零执行状态
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="axis"></param>
        /// <param name="status">回零执行状态，1：回零完成，0：回零未完成</param>
        /// <returns></returns>
        int CardAxisGetHomeResult(int CardNo, int axis, ref ushort status);





        /// <summary>
        /// 设置减速轴停止时间
        /// </summary>
        /// <param name="axis">卡号</param>
        /// <param name="CardNo">轴号</param>
        /// <param name="stopTime">停止时间</param>
        /// <returns></returns>
        int SetAxisStopTime(int CardNo, int axis, double stopTime);




        /// <summary>
        /// 停止轴的运动
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="axis">轴号</param>
        /// <param name="stop_mode">0减速停,1急停</param>
        /// <returns></returns>
        int StopCardAxisMovement(int CardNo, int axis, int stop_mode);

        /// <summary>
        /// 建立插补坐标系
        /// </summary>
        /// <returns></returns>
        int CreatCardAxisInterpolateCoord(InterpolateMotetionParamModel imp);

        /// <summary>
        /// 清除插补坐标系
        /// </summary>
        /// <returns></returns>
        int ClearCardAxisInterpolateCoord();

        /// <summary>
        /// 设置插补参数 
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInterpolateVectorProfile(InterpolateMotetionParamModel imp);

        /// <summary>
        /// 设置插补初始速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInterpolateMaxVel();


        /// <summary>
        /// 设置插补减速度
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInterpolateDecVel();

        /// <summary>
        /// 设置插补加加速
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInterpolateJerkVel();

        /// <summary>
        /// 设置插补低速
        /// </summary>
        /// <returns></returns>
        int SetCardAxisInterpolateSlowVel();







        /// <summary>
        /// 启动多轴空间直线插补
        /// </summary>
        /// <returns></returns>
        int CardAxesLineUnit(LineInterpolateparamModel line);

        /// <summary>
        /// 启动多轴空间圆弧插补
        /// </summary>
        /// <returns></returns>
        int CardAxesArcMoveCenterUnit(ArcInterpolateparamModel arc);

        /// <summary>
        /// 启动两轴平面连续直线插补
        /// </summary>
        /// <returns></returns>
        int CardAxisContiLineUnitStart(LineInterpolateparamModel line);

        /// <summary>
        /// 启动两轴平面连续圆弧插补
        /// </summary>
        /// <returns></returns>
        int CardAxisContiArcMoveStart(ArcInterpolateparamModel arc);

        /// <summary>
        /// 设置连续插补前瞻模式
        /// </summary>
        /// <param name="impm">插补运动参数（打开关闭前瞻）
        /// <para>"CardNo"控制卡卡号</para>
        /// <para>"Crd"坐标系号，取值范围：0~5</para>
        /// <para>"enable"比较功能状态，0：禁止，1：使能</para>
        /// <para>"LookaheadSegments"</para>
        /// <para>"PathError"</para>
        /// <para>"LookaheadAcc"</para></param>
        /// <returns></returns>
        int SetCardContiLookaheadMode(InterpolateMotetionParamModel impm);









        /// <summary>
        /// 配置高速比较器关联
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="hcmp"></param>
        /// <param name="axis"></param>
        /// <param name="cmp_source"></param>
        /// <param name="cmp_logic"></param>
        /// <param name="time"></param>
        /// <returns></returns>
        int SetCardAxisHcmpConfig(int CardNo, int hcmp, int axis, int cmp_source, int cmp_logic, int time);












        ///// <summary>
        ///// 设置二维位置比较输出数据
        ///// </summary>
        ///// <returns></returns>
        //int SetCardCompareConfigExternDate(PositionComparatorParamModel pcpm);



        /// <summary>
        /// 错误时设置停止模式(减速停止、突然停止)
        /// </summary>
        /// <param name="axis">轴号</param>
        /// <param name="stop_mode">停止模式(0:减速停止、1:突然停止)</param>
        /// <returns>正常返回 0；  出现错误时返回非 0 值；</returns>
        int SetCardAxisErrorStopMode(int axis, int stop_mode);

        /// <summary>
        /// 设定告警信号有效电平，可以为高电平有效，也可以为低电平有效，默认为低电平有效。 DI0—3 可在硬件上连接 XYZU 轴的告警 ALM 信号。用此函数可查询轴告警状态电平
        /// </summary>
        /// <param name="axis">轴号 </param>
        /// <param name="enable">告警信号使能</param>
        /// <param name="active_level">限位信号电平选择  <para>0 低电平有效</para>  <para>1 高电平有效</para></param>
        /// <returns>正常返回 0；  出现错误时返回非 0 值；</returns>
        int SetCardAxisAlarm(int axis, int enable, int active_level);

        /// <summary>
        /// 设置正负原点的限位
        /// </summary>
        /// <param name="axis">轴</param>
        /// <param name="ORGPlusPos">原点限位</param>
        /// <param name="PELAlarmPlusPos">正限位</param>
        /// <param name="NELAlarmPlusPos">负限位</param>
        /// <returns>正常返回 0；  出现错误时返回非 0 值；</returns>
        int SetSpacing(int axis, int ORGPlusPos, int PELAlarmPlusPos, int NELAlarmPlusPos);

        /// <summary>
        /// 设置轴参数状态
        /// </summary>
        /// <param name="axis">轴号</param>
        /// <param name="f">状态 true:置为1，false:置为0</param>
        /// <param name="kind">轴包含的元素</param>
        /// <returns></returns>
        int SetStatusParameter(int axis, bool f, AxisStatusParameterEnum kind);

        /// <summary>
        /// 返回支持直线插补的轴列表（轴索引）
        /// </summary>
        /// <returns></returns>
        List<int> GetLineInterpolationSupportAxis();



    }
}
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓​⁣​
