﻿// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ◆温⁠启‎志‎◆‎编⁠写​◇⁣微‌信⁠﹕‍1‎8‎7‌◆‏1​9‌3‍6‍◇‏1‌3‌9‏9‌　​※⁣保‌留‏所‏有⁣权‏利⁠请⁠勿‏删‎除‎◇​⁣​
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ────────────────────────────────────────────────────────────────
// 移植自 SamsunMotion / SMotorse 运动控制卡层参考实现
//   源: ICard/ICard.cs
//   改动: 仅行尾归一化为 LF、加 #nullable disable；命名空间与逻辑保持原样。
// ────────────────────────────────────────────────────────────────
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Samsun.Domain.MotionCard.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

    public interface ICard
    {

        //string CardConfigFileName { get; set; }

        /// <summary>
        /// 硬件拔码的卡号
        /// </summary>
        //int HardwarePullCodeCardNo { get; set; }

        /// <summary>
        /// 卡已经打开
        /// </summary>
        bool isOpen { get; set; }


        /// <summary>
        /// 卡已经初始化
        /// </summary>
        bool isInit { get; set; }


        /// <summary>
        /// 虚拟卡，方便脱机调试
        /// </summary>
        bool IsVitualCard { get; set; }


        /// <summary>
        /// 同型号多卡的数量
        /// </summary>
        ushort CardSum { get; set; }


        /// <summary>
        /// 运动卡输出IO的数量
        /// </summary>
        int CardOutputIOSum { get; set; }

        /// <summary>
        /// 运动卡输入IO的数量
        /// </summary>
        int CardInputIOSum { get; set; }

        /// <summary>
        /// 判断是否为离线模式
        /// </summary>
        bool IsOffineMode { get; set; }

        ///// <summary>
        ///// 如果是CAN总线IO扩展卡，要指定节点号，如果有多张用逗号分隔
        ///// </summary>
        //string CANIOCardNodes { get; set; }


        ///// <summary>
        ///// 卡是否设置拓展模块
        ///// </summary>
        //ExtendIoEnum ExtendMode { get; set; }

        ///// <summary>
        ///// 扩展IO模块的数量
        ///// </summary>
        // ushort ExtendIOSum { get; set; }


        /// <summary>
        /// 硬件名字,这里用枚举，以方便程序中轮询卡
        /// </summary>
        SystemSupportMotionCardEnum HardwareName { get; set; }



        /// <summary>
        /// 卡参数列表
        /// </summary>
        List<CardParamModel> ListCardParam { get; set; }

        /// <summary>
        /// 总线卡时，取总线错误
        /// </summary>
        /// <param name="ErrNum"></param>
        /// <returns></returns>
        string GetEtherCATErrorInfo(int ErrNum);


        /// <summary>
        /// SDK调用返回值的错误描述
        /// </summary>
        /// <param name="ErrNum"></param>
        /// <returns></returns>
        string GetErrorInfo(int ErrNum);

        /// <summary>
        /// 读取卡的当前状态(如果是总线卡，则读总线状态） 
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="channel">对于总线卡，此值固定为2</param>
        /// <returns></returns>
        int GetCardCurrentState(int CardNo, int channel);




        /// <summary>
        /// 控制卡初始化函数
        /// </summary>
        /// <returns>卡的数量</returns>
        int InitCard();

        /// <summary>
        /// 获取当前卡的轴数 
        /// </summary>
        /// <param name="CardNo">卡号</param>
        /// <param name="TotalAxis">返回当前卡的轴数</param>
        /// <returns>错误代码</returns>
        int GetCardTotalAxisNum(int CardNo, ref UInt32 TotalAxis);

        /// <summary>
        /// 设置 CAN 通讯状态
        /// <para>注 意：</para>
        /// <para>1）当关闭运动控制卡时，CAN 通讯不会被自动断开；当再次初始化运动控制卡时，  CAN-IO 通讯依然保持之前的状态；</para>
        /// <para>2）当连接 CAN 通讯时，必须使用 nmc_get_can_state 函数读取 CAN-IO 的通讯状态， 确认 CAN 通讯已正常连接。当连接出现异常时，可再次调用 nmc_set_can_state函数进行连接；</para>
        /// <para>3）设置波特率时需保证控制卡波特率与模块波特率相对应；</para>
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="NodeNum">CAN 节点数，取值范围：1~8</param>
        /// <param name="state">设置通讯状态，0：断开，1：连接</param>
        /// <param name="baud">设置控制卡波特率<para>波特率参数：0,1,2,3,4,5</para><para>对应波特率：1000Kbps，800Kbps,500Kbps,250Kbps,125Kbps,100Kbps</para></param>
        /// <returns></returns>
        int SetCardCANIOConnectState(int CardNo, int NodeNum, int state, int baud);

        /// <summary>
        /// 读取 CAN 通讯状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="NodeNum">返回 CAN 节点数</param>
        /// <param name="state">返回 CAN-IO 通讯状态，0：断开，1：连接，2：异常</param>
        /// <returns>错误代码</returns>
        int GetCardCANIOConnectState(int CardNo, ref UInt16 NodeNum, ref UInt16 state);

        /// <summary>
        /// 打开卡
        /// </summary>
        /// <param name="cardnum">返回初始化成功的卡数 </param>
        /// <param name="cardtypes">返回控制卡固件类型数组</param>
        /// <param name="CardID">返回控制卡硬件 ID 号数组，卡号按从小到大顺序排列  </param>
        /// <returns>错误代码，返回零为成功，大于0的数表示第几张卡打开出错</returns>
        int OpenCard(ref ushort cardnum, ref uint[] cardtypes, ref ushort[] CardNos);

        /// <summary>
        /// 获取控制卡动态库文件版本号
        /// </summary>
        /// <param name="LibVer">返回库版本号</param>
        /// <returns>错误代码</returns>
        int GetCardLibVersion(int CardID, ref int LibVer, ref int pDriver_ver, ref int pLogic_ver);

        /// <summary>
        /// 设置卡参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="PortNum">EtherCAT 端口号，固定为 2</param>
        /// <param name="Baudrate">参数不明等待回应</param>
        /// <param name="NodeCnt">参数不明等待回应</param>
        /// <param name="MasterId">参数不明等待回应</param>
        /// <returns>错误代码</returns>
        int SetCardMasterParam(int CardID, int PortNum, int Baudrate, int NodeCnt, int MasterId);

        /// <summary>
        /// 获取卡参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="PortNum">EtherCAT 端口号，固定为 2</param>
        /// <param name="Baudrate">参数不明等待回应</param>
        /// <param name="NodeCnt">参数不明等待回应</param>
        /// <param name="MasterId">参数不明等待回应</param>
        /// <returns>错误代码</returns>
        int GetCardMasterParam(int CardNo, int PortNum, ref ushort Baudrate, ref uint NodeCnt, ref ushort MasterId);


        ///// <summary>
        ///// 设置从站的配置
        ///// </summary>
        ///// <returns></returns>
        //int SetCardSlaveStationConfig();


        /// <summary>
        /// 获取从站配置信息
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="axis">EtherCAT 总线轴号</param>
        /// <param name="SlaveAddr">EtherCAT 总线轴地址</param>
        /// <param name="Sub_SlaveAddr">EtherCAT 总线轴子地址</param>
        /// <returns>错误代码</returns>
        int GetCardSlaveStationConfig(int CardNo, int axis, int lenght, ref ushort SlaveAddr, ref ushort Sub_SlaveAddr, ref int value);

        /// <summary>
        /// 设置主站的扫描周期
        /// </summary>
        /// <returns></returns>
        int SetCardMasterScanCycleTime(int CardNo, int FieldbusType, int CycleTime);

        /// <summary>
        /// 设置EtherCAT总线循环周期 
        /// </summary>
        /// <param name="CardNo">控制卡卡号 </param>
        /// <param name="Fieldbustype">  EtherCAT 端口号，固定为 2</param>
        /// <param name="CycleTime">CAT 总线循环周期，单位：us，支持 250/500/1000/</param>
        /// <returns>错误代码</returns>
        int GetCardMasterScanCycleTime(int CardNo, int FieldbusType, ref int CyclFieldbusTypeeTime);

        /// <summary>
        /// 控制卡初始复位（适用于EtherCAT总线卡）
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <returns>错误代码</returns>
        int CardReset(int CardNo);

        /// <summary>
        ///硬件复位（适用于所有脉冲/总线卡）
        /// </summary>
        /// <returns>错误代码</returns>
        int CardBoardReset();



        /// <summary>
        /// 总线卡总线复位
        /// </summary>
        /// <param name="CardNo"></param>
        /// <returns></returns>
        int CardSoftReset(ushort CardNo);



        /// <summary>
        /// 控制卡冷复位（适用于所有脉冲/总线卡）
        /// </summary>
        /// <returns>错误代码</returns>
        int CardCoolReset(ushort CardNo);

        /// <summary>
        /// 关闭控制卡（适用于所有脉冲/总线卡）
        /// </summary>
        /// <returns>错误代码</returns>
        int CloseCard();

        /// <summary>
        /// 指令缓冲区事件驱动器
        /// </summary>
        /// <param name="m_Obj"></param>
        /// <returns></returns>
        int DMCEventData(DMC_CacheMemory_Struct m_Obj);

        /// <summary>
        /// 设置硬急停参数
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="io_Port">io 端口数组列表，最大长度为 io_port(16)</param>
        /// <param name="enable">允许/禁止硬件信号功能,0:禁止,1:允许；</param>
        /// <param name="emg_logic">有效电平,0:低有效,1:高有效；</param>
        /// <param name="stop_mode">停止模式,0:减速停止,1:紧急停止，默认值 1。</param>
        /// <param name="filter_time">滤波时间时间:单位:毫秒(ms)</param>
        /// <returns></returns>
        int ConfigureEMGConfig(int CardNo, ushort[] io_Port, ushort enable, ushort emg_logic, ushort stop_mode, double filter_time);
    }
}
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓​⁣​
