﻿// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ◆温⁠启‎志‎◆‎编⁠写​◇⁣微‌信⁠﹕‍1‎8‎7‌◆‏1​9‌3‍6‍◇‏1‌3‌9‏9‌　​※⁣保‌留‏所‏有⁣权‏利⁠请⁠勿‏删‎除‎◇​⁣​
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ────────────────────────────────────────────────────────────────
// 移植自 SamsunMotion / SMotorse 运动控制卡层参考实现
//   源: CIO/IIOInPut.cs
//   改动: 仅行尾归一化为 LF、加 #nullable disable；命名空间与逻辑保持原样。
// ────────────────────────────────────────────────────────────────
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Samsun.Domain.MotionCard.Common
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public interface IIOInPut
    {
        /// <summary>
        /// IO的初始电平为高电平
        /// </summary>
        bool DefaultLevelIsHigh { get; set; }
        /// <summary>
        /// 硬件卡拥有的输入IO的数量
        /// </summary>
        ushort InIONums { get; set; }
        /// <summary>
        /// 输入IO所属卡的名字
        /// </summary>
        string InIOName { get; set; }


        /// <summary>
        /// IO端口号是从0开始还是从1开始（每种卡都可能有差别，注意看手册）  by lxy 2022/3/7
        /// </summary>
        int IOIndexStart { get; set; }


        /// <summary>
        /// 卡号（即这个输入IO对象是属于第几张卡的）
        /// </summary>
        int CardNo { get; set; }


        /// <summary>
        /// 是否为虚拟IO
        /// </summary>
        bool IsVitualIO { get; set; }


        /// <summary>
        /// 获取所有输入端口的值dmc_read_inport
        /// </summary>
        /// <returns></returns>
        int GetCardInPortValue(int CardNo, int portno);

        /// <summary>
        /// 检测急停IO，如果触发则停止全部轴
        /// </summary>
        /// <param name="CardName"></param>
        /// <param name="EmgIO"></param>
        /// <returns></returns>
        int EMGAction(string CardName, int cardNo, int EmgIO);


        /// <summary>
        /// 读取指定 EtherCAT 扩展模块的输入口组的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NoteID">EtherCAT 地址，从 1001 开始，按从站数往后累加</param>
        /// <param name="PortNo">输入组号（32 位一组，从 0 开始，如 0 表示 0-31 位，1 表示 32-63位）</param>
        /// <param name="IoValue">输入组各输入端口的值，bit0~bit31 的值分别代表第 0~31 号输入口的电平，1：低电平，0：高电平</param>
        /// <returns></returns>
        int NmcReadInportExtern(int CardNo, int Channel, int NoteID, int PortNo, ref uint IoValue);





        /// <summary>
        /// 读取指定 CAN-IO 扩展模块的输入端口的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="NodeID">CAN 节点号，取值范围：1~8</param>
        /// <param name="PortNo">端口号，0 表示 0~31 号口，1 表示 32~63 号口</param>
        /// <param name="IoValue">输出端口的值，bit0~bit31 的值分别代表第 0~31 号输出口的电平 </param>
        /// <returns>错误代码</returns>
        uint GetCardCANIOInPort(int CardNo, int NodeID, int PortNo, ref UInt32 IoValue);


        /// <summary>
        /// 设置主板上输入IO的端口的电平（虚拟运动卡专用）
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="bitno"></param>
        /// <param name="on_off"></param>
        /// <returns></returns>
        int SetCardWriteInBit(int CardNo, int bitno, int on_off);

        /// <summary>
        /// 设置主板上扩展模块输入IO的端口的电平（虚拟运动卡专用）
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="bitno"></param>
        /// <param name="nodeno"></param>
        /// <param name="on_off"></param>
        /// <returns></returns>
        int SetCardWriteExtendInBit(int CardNo, int bitno, int nodeno, int on_off);

        /// <summary>
        /// 读取指定输入端口的状态
        /// </summary>
        /// <returns></returns>
        int GetCardInPortNoValue(int CardNo, int portno);

        /// <summary>
        /// 读取指定扩展输入端口的状态
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NoteID">站号</param>
        /// <param name="IoBit">输入端口号</param>
        /// <param name="IoValue">指定输出端口的电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        int NmcGetCardReadInBit(int CardNo, int Channel, int NoteID, int IoBit, ref ushort IoValue);


        /// <summary>
        /// 查询 DI 端口的状态。 DI0—3 可在硬件上连接 XYZU 轴的告警 ALM 信号。用此函数可查询轴告警状态(Pci9014)
        /// </summary>
        /// <param name="card_no">卡号 </param>
        /// <param name="pData">DI 端口状态，其中的 bit 0 ~15 分别对应端子上的 DI0~DI15  <para> 当*pData 中的位为 0 时，对应端子输入低电平；</para> <para> 当*pData 中的位为 1 时，对应端子输入高电平；</para>    </param>
        /// <returns>正常返回 0；  出现错误时返回非 0 值；</returns>
        int GetCardDIState(int card_no, ref int pData);

        int GetCardDIBitAlarmState(int card_no, int bit_no, ref int pData);

        /// <summary>
        /// 设置卡Com口使能
        /// </summary>
        int SetCardCompEnable(int card_no, int enable, int active_level, int ref_source, int length);
    }


    public class IOInPutClass
    {
        /// <summary>
        /// 卡参数列表
        /// </summary>
        public List<CardParamModel> ListCardParam { get; set; }

        /// <summary>
        /// IO的初始电平为高电平
        /// </summary>
        public bool DefaultLevelIsHigh { get; set; }
        /// <summary>
        /// 硬件卡拥有的输入IO的数量
        /// </summary>
        public ushort InIONums { get; set; }
        /// <summary>
        /// 输入IO所属卡的名字
        /// </summary>
        public string InIOName { get; set; }


        /// <summary>
        /// IO端口号是从0开始还是从1开始（每种卡都可能有差别，注意看手册）  by lxy 2022/3/7
        /// </summary>
        public int IOIndexStart { get; set; }


        /// <summary>
        /// 卡号（即这个输入IO对象是属于第几张卡的）
        /// </summary>
        public int CardNo { get; set; }


        /// <summary>
        /// 是否为虚拟IO
        /// </summary>
        public bool IsVitualIO { get; set; }
    }

}
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓​⁣​
