﻿// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ◆温⁠启‎志‎◆‎编⁠写​◇⁣微‌信⁠﹕‍1‎8‎7‌◆‏1​9‌3‍6‍◇‏1‌3‌9‏9‌　​※⁣保‌留‏所‏有⁣权‏利⁠请⁠勿‏删‎除‎◇​⁣​
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓✦​⁣​
// ────────────────────────────────────────────────────────────────
// 移植自 SamsunMotion / SMotorse 运动控制卡层参考实现
//   源: CIO/IIOOutPut.cs
//   改动: 仅行尾归一化为 LF、加 #nullable disable；命名空间与逻辑保持原样。
// ────────────────────────────────────────────────────────────────
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Samsun.Domain.MotionCard.Common
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public interface IIOOutPut
    {
        /// <summary>
        /// IO的初始电平为高电平
        /// </summary>
        bool DefaultLevelIsHigh { get; set; }
        /// <summary>
        /// 硬件卡拥有的输出IO的数量
        /// </summary>
        ushort OutIONums { get; set; }
        /// <summary>
        /// 输入IO所属卡的名字
        /// </summary>
        string OutIOName { get; set; }


        //modify by 1015
        /// <summary>
        /// 卡号（即这个输出IO对象是属于第几张卡的）
        /// </summary>
        int CardNo { get; set; }


        /// <summary>
        /// IO端口号是从0开始还是从1开始（每种卡都可能有差别，注意看手册）  by lxy 2022/3/7
        /// </summary>
        int IOIndexStart { get; set; }



        /// <summary>
        /// 是否为虚拟IO
        /// </summary>
        bool IsVitualIO { get; set; }



        /// <summary>
        /// 读取指定输出端口的状态
        /// </summary>
        /// <returns></returns>
        int GetCardPortNoOutState(int CardNo, int bitno);
        /// <summary>
        /// 读取所有输出端口的状态
        /// </summary>
        /// <returns></returns>
        uint GetCardOutState(int CardNo, int portno);


        /// <summary>
        /// 设置指定控制卡的某个输出端口的电平
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="bitno"></param>
        /// <param name="on_off"></param>
        /// <returns></returns>
        int SetCardBitNoInBit(int CardNo, int bitno, int on_off);

        /// <summary>
        /// 读取指定 EtherCAT 扩展模块的输出口组的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NoteID">EtherCAT 地址，从 1001 开始，按从站数往后累加</param>
        /// <param name="PortNo">输出组号（32 位一组，从 0 开始，如 0 表示 0-31 位，1 表示 32-63位）</param>
        /// <param name="IoValue">输出组各输出端口的值，bit0 ~bit31 的值分别代表第 0~31 号输出口的电平，1：低电平，0：高电平</param>
        /// <returns>错误代码</returns>
        int NmcReadOutportExtern(int CardNo, int Channel, int NoteID, int PortNo, ref uint IoValue);


        /// <summary>
        /// 设置指定 EtherCAT 扩展模块的某个输出端口的电平(0：低电平，1：高电平)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NoteID">EtherCAT 地址，从 1001 开始，按从站数往后累加</param>
        /// <param name="IoBit">输出端口号</param>
        /// <param name="IoValue">指定输出端口的电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        int NmcWriteOutbitExtern(int CardNo, int Channel, int NoteID, int IoBit, ushort IoValue);

        /// <summary>
        /// 设置指定 EtherCAT 扩展模块的输出口组的电平(0：低电平，1：高电平)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NodeID">EtherCAT 地址，从 1001 开始，按从站数往后累加</param>
        /// <param name="portno">输出组号（32 位一组，从 0 开始，如 0 表示 0-31 位，1 表示 32-63位）</param>
        /// <param name="Iovalue">输出组各输出端口的值，bit0~bit31 的值分别代表第 0~31 号输出口的电平，1：低电平，0：高电平</param>
        /// <returns></returns>
        int NmcWriteOutPortExtern(int CardNo, int Channel, int NodeID, ushort portno, uint Iovalue);
        /// <summary>
        /// 读取指定 EtherCAT 扩展模块的某个输出端口的电平(0：低电平，1：高电平)
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="Channel">总线通道号，固定为 2</param>
        /// <param name="NoteID">EtherCAT 地址，从 1001 开始，按从站数往后累加</param>
        /// <param name="IoBit">输出端口号</param>
        /// <param name="IoValue">指定输出端口的电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        uint NmcGetCardReadOutBit(int CardNo, int Channel, int NoteID, int IoBit, ref ushort IoValue);

        /// <summary>
        /// 设置指定 CAN-IO 扩展模块的某个输出端口的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="NodeID">CAN 节点号，取值范围：1~8</param>
        /// <param name="IoBit">输出口号</param>
        /// <param name="IoValue">输出电平，0：低电平，1：高电平</param>
        /// <returns>错误代码</returns>
        int SetCardCANIOOutBit(int CardNo, int NodeID, int IoBit, int IoValue);


        /// <summary>
        /// 读取指定 CAN-IO 扩展模块的输出端口的电平
        /// </summary>
        /// <param name="CardNo">控制卡卡号</param>
        /// <param name="NodeID">CAN 节点号，取值范围：1~8</param>
        /// <param name="PortNo">端口号，0 表示 0~31 号口，1 表示 32~63 号口</param>
        /// <param name="IoValue">输出端口的值，bit0~bit31 的值分别代表第 0~31 号输出口的电平 </param>
        /// <returns></returns>
        uint GetCardCANIOOutPort(int CardNo, int NodeID, int PortNo, ref UInt32 IoValue);

        /// <summary>
        /// 设置指定控制卡的全部输出口的电平
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="portno"></param>
        /// <param name="outport_val"></param>
        /// <returns></returns>
        int SetCardPortNoOutPort(int CardNo, int portno, uint outport_va);

        /// <summary>
        /// 读取位置比较输出口的状态
        /// </summary>
        /// <returns></returns>
        int GetLocationIsOutNoState();
        /// <summary>
        /// 设置位置比较输出口的状态
        /// </summary>
        /// <returns></returns>
        int SetLocationIsOutNoState();

        /// <summary>
        /// 设置 DO 端口输出状态 
        /// </summary>
        /// <param name="CardNo"></param>
        /// <param name="data"></param>
        /// <returns></returns>
        int SetCardDOOut(int CardNo, int data);

        /// <summary>
        /// 设置 DO 端口中指定位的状态
        /// </summary>
        int SetCardDOBitState(int card_no, int bit_no, int data);



        /// <summary>
        /// 读取 DO 端口的状态。 
        /// </summary>
        int GetCardDOState(int card_no, ref int pData);
    }


    public class IIOOutPutClass
    {
        /// <summary>
        /// 卡参数列表
        /// </summary>
        public List<CardParamModel> ListCardParam { get; set; }

        /// <summary>
        /// IO的初始电平为高电平
        /// </summary>
        public bool DefaultLevelIsHigh { get; set; }
        /// <summary>
        /// 硬件卡拥有的输出IO的数量
        /// </summary>
        public ushort OutIONums { get; set; }
        /// <summary>
        /// 输入IO所属卡的名字
        /// </summary>
        public string OutIOName { get; set; }


        //modify by 1015
        /// <summary>
        /// 卡号（即这个输出IO对象是属于第几张卡的）
        /// </summary>
        public int CardNo { get; set; }


        /// <summary>
        /// IO端口号是从0开始还是从1开始（每种卡都可能有差别，注意看手册）  by lxy 2022/3/7
        /// </summary>
        public int IOIndexStart { get; set; }



        /// <summary>
        /// 是否为虚拟IO
        /// </summary>
        public bool IsVitualIO { get; set; }

    }


}
// ◆◇※▣▤▥▦▧▨▩░▒▓✦✧⚝☢☣➤◈❖◆◇※▣▤▥▦▧▨▩░▒▓​⁣​
